// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: competition.proto
package org.example.javaFiles;
// Protobuf Java Version: 4.26.1
public interface ChildDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChildDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string age = 3;</code>
   * @return The age.
   */
  java.lang.String getAge();
  /**
   * <code>string age = 3;</code>
   * @return The bytes for age.
   */
  com.google.protobuf.ByteString
      getAgeBytes();

  /**
   * <code>string number = 4;</code>
   * @return The number.
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 4;</code>
   * @return The bytes for number.
   */
  com.google.protobuf.ByteString
      getNumberBytes();
}
