// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: competition.proto

// Protobuf Java Version: 4.26.1
/**
 * Protobuf type {@code CompetitionRequest}
 */
package org.example.javaFiles;
public final class CompetitionRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:CompetitionRequest)
    CompetitionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      CompetitionRequest.class.getName());
  }
  // Use CompetitionRequest.newBuilder() to construct.
  private CompetitionRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CompetitionRequest() {
    type_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CompetitionProtobuf.internal_static_CompetitionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CompetitionProtobuf.internal_static_CompetitionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CompetitionRequest.class, CompetitionRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code CompetitionRequest.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unknown = 0;</code>
     */
    Unknown(0),
    /**
     * <code>LOGIN = 1;</code>
     */
    LOGIN(1),
    /**
     * <code>LOGOUT = 2;</code>
     */
    LOGOUT(2),
    /**
     * <code>FIND_ORGANIZING = 3;</code>
     */
    FIND_ORGANIZING(3),
    /**
     * <code>NUMBER_OF_CHILDREN_FOR_SAMPLE = 4;</code>
     */
    NUMBER_OF_CHILDREN_FOR_SAMPLE(4),
    /**
     * <code>FIND_ALL_SAMPLES = 5;</code>
     */
    FIND_ALL_SAMPLES(5),
    /**
     * <code>FIND_SAMPLE = 6;</code>
     */
    FIND_SAMPLE(6),
    /**
     * <code>REGISTER_CHILD = 7;</code>
     */
    REGISTER_CHILD(7),
    /**
     * <code>FIND_CHILD = 8;</code>
     */
    FIND_CHILD(8),
    /**
     * <code>SAVE_CHILD = 9;</code>
     */
    SAVE_CHILD(9),
    /**
     * <code>NEW = 10;</code>
     */
    NEW(10),
    /**
     * <code>LIST_CHILDREN_FOR_SAMPLE = 11;</code>
     */
    LIST_CHILDREN_FOR_SAMPLE(11),
    /**
     * <code>OK = 12;</code>
     */
    OK(12),
    /**
     * <code>ERROR = 13;</code>
     */
    ERROR(13),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Type.class.getName());
    }
    /**
     * <code>Unknown = 0;</code>
     */
    public static final int Unknown_VALUE = 0;
    /**
     * <code>LOGIN = 1;</code>
     */
    public static final int LOGIN_VALUE = 1;
    /**
     * <code>LOGOUT = 2;</code>
     */
    public static final int LOGOUT_VALUE = 2;
    /**
     * <code>FIND_ORGANIZING = 3;</code>
     */
    public static final int FIND_ORGANIZING_VALUE = 3;
    /**
     * <code>NUMBER_OF_CHILDREN_FOR_SAMPLE = 4;</code>
     */
    public static final int NUMBER_OF_CHILDREN_FOR_SAMPLE_VALUE = 4;
    /**
     * <code>FIND_ALL_SAMPLES = 5;</code>
     */
    public static final int FIND_ALL_SAMPLES_VALUE = 5;
    /**
     * <code>FIND_SAMPLE = 6;</code>
     */
    public static final int FIND_SAMPLE_VALUE = 6;
    /**
     * <code>REGISTER_CHILD = 7;</code>
     */
    public static final int REGISTER_CHILD_VALUE = 7;
    /**
     * <code>FIND_CHILD = 8;</code>
     */
    public static final int FIND_CHILD_VALUE = 8;
    /**
     * <code>SAVE_CHILD = 9;</code>
     */
    public static final int SAVE_CHILD_VALUE = 9;
    /**
     * <code>NEW = 10;</code>
     */
    public static final int NEW_VALUE = 10;
    /**
     * <code>LIST_CHILDREN_FOR_SAMPLE = 11;</code>
     */
    public static final int LIST_CHILDREN_FOR_SAMPLE_VALUE = 11;
    /**
     * <code>OK = 12;</code>
     */
    public static final int OK_VALUE = 12;
    /**
     * <code>ERROR = 13;</code>
     */
    public static final int ERROR_VALUE = 13;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return Unknown;
        case 1: return LOGIN;
        case 2: return LOGOUT;
        case 3: return FIND_ORGANIZING;
        case 4: return NUMBER_OF_CHILDREN_FOR_SAMPLE;
        case 5: return FIND_ALL_SAMPLES;
        case 6: return FIND_SAMPLE;
        case 7: return REGISTER_CHILD;
        case 8: return FIND_CHILD;
        case 9: return SAVE_CHILD;
        case 10: return NEW;
        case 11: return LIST_CHILDREN_FOR_SAMPLE;
        case 12: return OK;
        case 13: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CompetitionRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CompetitionRequest.Type)
  }

  private int playloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object playload_;
  public enum PlayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ORGANIZING(1),
    ORGANIZING_LOGOUT(2),
    ORGANIZING_FIND(3),
    SAMPLE(4),
    EMPTY(5),
    SAMPLE_FIND(6),
    REGISTRATION(7),
    CHILD(8),
    CHILD_SAVED(9),
    SAMPLES(11),
    NEW(10),
    PLAYLOAD_NOT_SET(0);
    private final int value;
    private PlayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PlayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PlayloadCase forNumber(int value) {
      switch (value) {
        case 1: return ORGANIZING;
        case 2: return ORGANIZING_LOGOUT;
        case 3: return ORGANIZING_FIND;
        case 4: return SAMPLE;
        case 5: return EMPTY;
        case 6: return SAMPLE_FIND;
        case 7: return REGISTRATION;
        case 8: return CHILD;
        case 9: return CHILD_SAVED;
        case 11: return SAMPLES;
        case 10: return NEW;
        case 0: return PLAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PlayloadCase
  getPlayloadCase() {
    return PlayloadCase.forNumber(
        playloadCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 12;
  private int type_ = 0;
  /**
   * <pre>
   * Identifies which request is filled in.
   * </pre>
   *
   * <code>.CompetitionRequest.Type type = 12;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * Identifies which request is filled in.
   * </pre>
   *
   * <code>.CompetitionRequest.Type type = 12;</code>
   * @return The type.
   */
  @java.lang.Override public CompetitionRequest.Type getType() {
    CompetitionRequest.Type result = CompetitionRequest.Type.forNumber(type_);
    return result == null ? CompetitionRequest.Type.UNRECOGNIZED : result;
  }

  public static final int ORGANIZING_FIELD_NUMBER = 1;
  /**
   * <pre>
   * One of the following will be filled in, depending on the type.
   * </pre>
   *
   * <code>.OrganizingDTO organizing = 1;</code>
   * @return Whether the organizing field is set.
   */
  @java.lang.Override
  public boolean hasOrganizing() {
    return playloadCase_ == 1;
  }
  /**
   * <pre>
   * One of the following will be filled in, depending on the type.
   * </pre>
   *
   * <code>.OrganizingDTO organizing = 1;</code>
   * @return The organizing.
   */
  @java.lang.Override
  public OrganizingDTO getOrganizing() {
    if (playloadCase_ == 1) {
       return (OrganizingDTO) playload_;
    }
    return OrganizingDTO.getDefaultInstance();
  }
  /**
   * <pre>
   * One of the following will be filled in, depending on the type.
   * </pre>
   *
   * <code>.OrganizingDTO organizing = 1;</code>
   */
  @java.lang.Override
  public OrganizingDTOOrBuilder getOrganizingOrBuilder() {
    if (playloadCase_ == 1) {
       return (OrganizingDTO) playload_;
    }
    return OrganizingDTO.getDefaultInstance();
  }

  public static final int ORGANIZING_LOGOUT_FIELD_NUMBER = 2;
  /**
   * <code>.OrganizingDTO organizing_logout = 2;</code>
   * @return Whether the organizingLogout field is set.
   */
  @java.lang.Override
  public boolean hasOrganizingLogout() {
    return playloadCase_ == 2;
  }
  /**
   * <code>.OrganizingDTO organizing_logout = 2;</code>
   * @return The organizingLogout.
   */
  @java.lang.Override
  public OrganizingDTO getOrganizingLogout() {
    if (playloadCase_ == 2) {
       return (OrganizingDTO) playload_;
    }
    return OrganizingDTO.getDefaultInstance();
  }
  /**
   * <code>.OrganizingDTO organizing_logout = 2;</code>
   */
  @java.lang.Override
  public OrganizingDTOOrBuilder getOrganizingLogoutOrBuilder() {
    if (playloadCase_ == 2) {
       return (OrganizingDTO) playload_;
    }
    return OrganizingDTO.getDefaultInstance();
  }

  public static final int ORGANIZING_FIND_FIELD_NUMBER = 3;
  /**
   * <code>.OrganizingDTO organizing_find = 3;</code>
   * @return Whether the organizingFind field is set.
   */
  @java.lang.Override
  public boolean hasOrganizingFind() {
    return playloadCase_ == 3;
  }
  /**
   * <code>.OrganizingDTO organizing_find = 3;</code>
   * @return The organizingFind.
   */
  @java.lang.Override
  public OrganizingDTO getOrganizingFind() {
    if (playloadCase_ == 3) {
       return (OrganizingDTO) playload_;
    }
    return OrganizingDTO.getDefaultInstance();
  }
  /**
   * <code>.OrganizingDTO organizing_find = 3;</code>
   */
  @java.lang.Override
  public OrganizingDTOOrBuilder getOrganizingFindOrBuilder() {
    if (playloadCase_ == 3) {
       return (OrganizingDTO) playload_;
    }
    return OrganizingDTO.getDefaultInstance();
  }

  public static final int SAMPLE_FIELD_NUMBER = 4;
  /**
   * <code>.SampleDTO sample = 4;</code>
   * @return Whether the sample field is set.
   */
  @java.lang.Override
  public boolean hasSample() {
    return playloadCase_ == 4;
  }
  /**
   * <code>.SampleDTO sample = 4;</code>
   * @return The sample.
   */
  @java.lang.Override
  public SampleDTO getSample() {
    if (playloadCase_ == 4) {
       return (SampleDTO) playload_;
    }
    return SampleDTO.getDefaultInstance();
  }
  /**
   * <code>.SampleDTO sample = 4;</code>
   */
  @java.lang.Override
  public SampleDTOOrBuilder getSampleOrBuilder() {
    if (playloadCase_ == 4) {
       return (SampleDTO) playload_;
    }
    return SampleDTO.getDefaultInstance();
  }

  public static final int EMPTY_FIELD_NUMBER = 5;
  /**
   * <code>string empty = 5;</code>
   * @return Whether the empty field is set.
   */
  public boolean hasEmpty() {
    return playloadCase_ == 5;
  }
  /**
   * <code>string empty = 5;</code>
   * @return The empty.
   */
  public java.lang.String getEmpty() {
    java.lang.Object ref = "";
    if (playloadCase_ == 5) {
      ref = playload_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (playloadCase_ == 5) {
        playload_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string empty = 5;</code>
   * @return The bytes for empty.
   */
  public com.google.protobuf.ByteString
      getEmptyBytes() {
    java.lang.Object ref = "";
    if (playloadCase_ == 5) {
      ref = playload_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (playloadCase_ == 5) {
        playload_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SAMPLE_FIND_FIELD_NUMBER = 6;
  /**
   * <code>.SampleDTO sample_find = 6;</code>
   * @return Whether the sampleFind field is set.
   */
  @java.lang.Override
  public boolean hasSampleFind() {
    return playloadCase_ == 6;
  }
  /**
   * <code>.SampleDTO sample_find = 6;</code>
   * @return The sampleFind.
   */
  @java.lang.Override
  public SampleDTO getSampleFind() {
    if (playloadCase_ == 6) {
       return (SampleDTO) playload_;
    }
    return SampleDTO.getDefaultInstance();
  }
  /**
   * <code>.SampleDTO sample_find = 6;</code>
   */
  @java.lang.Override
  public SampleDTOOrBuilder getSampleFindOrBuilder() {
    if (playloadCase_ == 6) {
       return (SampleDTO) playload_;
    }
    return SampleDTO.getDefaultInstance();
  }

  public static final int REGISTRATION_FIELD_NUMBER = 7;
  /**
   * <code>.RegistrationDTO registration = 7;</code>
   * @return Whether the registration field is set.
   */
  @java.lang.Override
  public boolean hasRegistration() {
    return playloadCase_ == 7;
  }
  /**
   * <code>.RegistrationDTO registration = 7;</code>
   * @return The registration.
   */
  @java.lang.Override
  public RegistrationDTO getRegistration() {
    if (playloadCase_ == 7) {
       return (RegistrationDTO) playload_;
    }
    return RegistrationDTO.getDefaultInstance();
  }
  /**
   * <code>.RegistrationDTO registration = 7;</code>
   */
  @java.lang.Override
  public RegistrationDTOOrBuilder getRegistrationOrBuilder() {
    if (playloadCase_ == 7) {
       return (RegistrationDTO) playload_;
    }
    return RegistrationDTO.getDefaultInstance();
  }

  public static final int CHILD_FIELD_NUMBER = 8;
  /**
   * <code>.ChildDTO child = 8;</code>
   * @return Whether the child field is set.
   */
  @java.lang.Override
  public boolean hasChild() {
    return playloadCase_ == 8;
  }
  /**
   * <code>.ChildDTO child = 8;</code>
   * @return The child.
   */
  @java.lang.Override
  public ChildDTO getChild() {
    if (playloadCase_ == 8) {
       return (ChildDTO) playload_;
    }
    return ChildDTO.getDefaultInstance();
  }
  /**
   * <code>.ChildDTO child = 8;</code>
   */
  @java.lang.Override
  public ChildDTOOrBuilder getChildOrBuilder() {
    if (playloadCase_ == 8) {
       return (ChildDTO) playload_;
    }
    return ChildDTO.getDefaultInstance();
  }

  public static final int CHILD_SAVED_FIELD_NUMBER = 9;
  /**
   * <code>.ChildDTO child_saved = 9;</code>
   * @return Whether the childSaved field is set.
   */
  @java.lang.Override
  public boolean hasChildSaved() {
    return playloadCase_ == 9;
  }
  /**
   * <code>.ChildDTO child_saved = 9;</code>
   * @return The childSaved.
   */
  @java.lang.Override
  public ChildDTO getChildSaved() {
    if (playloadCase_ == 9) {
       return (ChildDTO) playload_;
    }
    return ChildDTO.getDefaultInstance();
  }
  /**
   * <code>.ChildDTO child_saved = 9;</code>
   */
  @java.lang.Override
  public ChildDTOOrBuilder getChildSavedOrBuilder() {
    if (playloadCase_ == 9) {
       return (ChildDTO) playload_;
    }
    return ChildDTO.getDefaultInstance();
  }

  public static final int SAMPLES_FIELD_NUMBER = 11;
  /**
   * <code>.SampleDTO samples = 11;</code>
   * @return Whether the samples field is set.
   */
  @java.lang.Override
  public boolean hasSamples() {
    return playloadCase_ == 11;
  }
  /**
   * <code>.SampleDTO samples = 11;</code>
   * @return The samples.
   */
  @java.lang.Override
  public SampleDTO getSamples() {
    if (playloadCase_ == 11) {
       return (SampleDTO) playload_;
    }
    return SampleDTO.getDefaultInstance();
  }
  /**
   * <code>.SampleDTO samples = 11;</code>
   */
  @java.lang.Override
  public SampleDTOOrBuilder getSamplesOrBuilder() {
    if (playloadCase_ == 11) {
       return (SampleDTO) playload_;
    }
    return SampleDTO.getDefaultInstance();
  }

  public static final int NEW_FIELD_NUMBER = 10;
  /**
   * <code>.New new = 10;</code>
   * @return Whether the new field is set.
   */
  @java.lang.Override
  public boolean hasNew() {
    return playloadCase_ == 10;
  }
  /**
   * <code>.New new = 10;</code>
   * @return The new.
   */
  @java.lang.Override
  public New getNew() {
    if (playloadCase_ == 10) {
       return (New) playload_;
    }
    return New.getDefaultInstance();
  }
  /**
   * <code>.New new = 10;</code>
   */
  @java.lang.Override
  public NewOrBuilder getNewOrBuilder() {
    if (playloadCase_ == 10) {
       return (New) playload_;
    }
    return New.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (playloadCase_ == 1) {
      output.writeMessage(1, (OrganizingDTO) playload_);
    }
    if (playloadCase_ == 2) {
      output.writeMessage(2, (OrganizingDTO) playload_);
    }
    if (playloadCase_ == 3) {
      output.writeMessage(3, (OrganizingDTO) playload_);
    }
    if (playloadCase_ == 4) {
      output.writeMessage(4, (SampleDTO) playload_);
    }
    if (playloadCase_ == 5) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, playload_);
    }
    if (playloadCase_ == 6) {
      output.writeMessage(6, (SampleDTO) playload_);
    }
    if (playloadCase_ == 7) {
      output.writeMessage(7, (RegistrationDTO) playload_);
    }
    if (playloadCase_ == 8) {
      output.writeMessage(8, (ChildDTO) playload_);
    }
    if (playloadCase_ == 9) {
      output.writeMessage(9, (ChildDTO) playload_);
    }
    if (playloadCase_ == 10) {
      output.writeMessage(10, (New) playload_);
    }
    if (playloadCase_ == 11) {
      output.writeMessage(11, (SampleDTO) playload_);
    }
    if (type_ != CompetitionRequest.Type.Unknown.getNumber()) {
      output.writeEnum(12, type_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (playloadCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (OrganizingDTO) playload_);
    }
    if (playloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (OrganizingDTO) playload_);
    }
    if (playloadCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (OrganizingDTO) playload_);
    }
    if (playloadCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (SampleDTO) playload_);
    }
    if (playloadCase_ == 5) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, playload_);
    }
    if (playloadCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (SampleDTO) playload_);
    }
    if (playloadCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (RegistrationDTO) playload_);
    }
    if (playloadCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (ChildDTO) playload_);
    }
    if (playloadCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (ChildDTO) playload_);
    }
    if (playloadCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (New) playload_);
    }
    if (playloadCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, (SampleDTO) playload_);
    }
    if (type_ != CompetitionRequest.Type.Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(12, type_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CompetitionRequest)) {
      return super.equals(obj);
    }
    CompetitionRequest other = (CompetitionRequest) obj;

    if (type_ != other.type_) return false;
    if (!getPlayloadCase().equals(other.getPlayloadCase())) return false;
    switch (playloadCase_) {
      case 1:
        if (!getOrganizing()
            .equals(other.getOrganizing())) return false;
        break;
      case 2:
        if (!getOrganizingLogout()
            .equals(other.getOrganizingLogout())) return false;
        break;
      case 3:
        if (!getOrganizingFind()
            .equals(other.getOrganizingFind())) return false;
        break;
      case 4:
        if (!getSample()
            .equals(other.getSample())) return false;
        break;
      case 5:
        if (!getEmpty()
            .equals(other.getEmpty())) return false;
        break;
      case 6:
        if (!getSampleFind()
            .equals(other.getSampleFind())) return false;
        break;
      case 7:
        if (!getRegistration()
            .equals(other.getRegistration())) return false;
        break;
      case 8:
        if (!getChild()
            .equals(other.getChild())) return false;
        break;
      case 9:
        if (!getChildSaved()
            .equals(other.getChildSaved())) return false;
        break;
      case 11:
        if (!getSamples()
            .equals(other.getSamples())) return false;
        break;
      case 10:
        if (!getNew()
            .equals(other.getNew())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (playloadCase_) {
      case 1:
        hash = (37 * hash) + ORGANIZING_FIELD_NUMBER;
        hash = (53 * hash) + getOrganizing().hashCode();
        break;
      case 2:
        hash = (37 * hash) + ORGANIZING_LOGOUT_FIELD_NUMBER;
        hash = (53 * hash) + getOrganizingLogout().hashCode();
        break;
      case 3:
        hash = (37 * hash) + ORGANIZING_FIND_FIELD_NUMBER;
        hash = (53 * hash) + getOrganizingFind().hashCode();
        break;
      case 4:
        hash = (37 * hash) + SAMPLE_FIELD_NUMBER;
        hash = (53 * hash) + getSample().hashCode();
        break;
      case 5:
        hash = (37 * hash) + EMPTY_FIELD_NUMBER;
        hash = (53 * hash) + getEmpty().hashCode();
        break;
      case 6:
        hash = (37 * hash) + SAMPLE_FIND_FIELD_NUMBER;
        hash = (53 * hash) + getSampleFind().hashCode();
        break;
      case 7:
        hash = (37 * hash) + REGISTRATION_FIELD_NUMBER;
        hash = (53 * hash) + getRegistration().hashCode();
        break;
      case 8:
        hash = (37 * hash) + CHILD_FIELD_NUMBER;
        hash = (53 * hash) + getChild().hashCode();
        break;
      case 9:
        hash = (37 * hash) + CHILD_SAVED_FIELD_NUMBER;
        hash = (53 * hash) + getChildSaved().hashCode();
        break;
      case 11:
        hash = (37 * hash) + SAMPLES_FIELD_NUMBER;
        hash = (53 * hash) + getSamples().hashCode();
        break;
      case 10:
        hash = (37 * hash) + NEW_FIELD_NUMBER;
        hash = (53 * hash) + getNew().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CompetitionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CompetitionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CompetitionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CompetitionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CompetitionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CompetitionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CompetitionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static CompetitionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static CompetitionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static CompetitionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CompetitionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static CompetitionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CompetitionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CompetitionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CompetitionRequest)
      CompetitionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CompetitionProtobuf.internal_static_CompetitionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CompetitionProtobuf.internal_static_CompetitionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CompetitionRequest.class, CompetitionRequest.Builder.class);
    }

    // Construct using CompetitionRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      if (organizingBuilder_ != null) {
        organizingBuilder_.clear();
      }
      if (organizingLogoutBuilder_ != null) {
        organizingLogoutBuilder_.clear();
      }
      if (organizingFindBuilder_ != null) {
        organizingFindBuilder_.clear();
      }
      if (sampleBuilder_ != null) {
        sampleBuilder_.clear();
      }
      if (sampleFindBuilder_ != null) {
        sampleFindBuilder_.clear();
      }
      if (registrationBuilder_ != null) {
        registrationBuilder_.clear();
      }
      if (childBuilder_ != null) {
        childBuilder_.clear();
      }
      if (childSavedBuilder_ != null) {
        childSavedBuilder_.clear();
      }
      if (samplesBuilder_ != null) {
        samplesBuilder_.clear();
      }
      if (newBuilder_ != null) {
        newBuilder_.clear();
      }
      playloadCase_ = 0;
      playload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CompetitionProtobuf.internal_static_CompetitionRequest_descriptor;
    }

    @java.lang.Override
    public CompetitionRequest getDefaultInstanceForType() {
      return CompetitionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public CompetitionRequest build() {
      CompetitionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CompetitionRequest buildPartial() {
      CompetitionRequest result = new CompetitionRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(CompetitionRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
    }

    private void buildPartialOneofs(CompetitionRequest result) {
      result.playloadCase_ = playloadCase_;
      result.playload_ = this.playload_;
      if (playloadCase_ == 1 &&
          organizingBuilder_ != null) {
        result.playload_ = organizingBuilder_.build();
      }
      if (playloadCase_ == 2 &&
          organizingLogoutBuilder_ != null) {
        result.playload_ = organizingLogoutBuilder_.build();
      }
      if (playloadCase_ == 3 &&
          organizingFindBuilder_ != null) {
        result.playload_ = organizingFindBuilder_.build();
      }
      if (playloadCase_ == 4 &&
          sampleBuilder_ != null) {
        result.playload_ = sampleBuilder_.build();
      }
      if (playloadCase_ == 6 &&
          sampleFindBuilder_ != null) {
        result.playload_ = sampleFindBuilder_.build();
      }
      if (playloadCase_ == 7 &&
          registrationBuilder_ != null) {
        result.playload_ = registrationBuilder_.build();
      }
      if (playloadCase_ == 8 &&
          childBuilder_ != null) {
        result.playload_ = childBuilder_.build();
      }
      if (playloadCase_ == 9 &&
          childSavedBuilder_ != null) {
        result.playload_ = childSavedBuilder_.build();
      }
      if (playloadCase_ == 11 &&
          samplesBuilder_ != null) {
        result.playload_ = samplesBuilder_.build();
      }
      if (playloadCase_ == 10 &&
          newBuilder_ != null) {
        result.playload_ = newBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CompetitionRequest) {
        return mergeFrom((CompetitionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CompetitionRequest other) {
      if (other == CompetitionRequest.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getPlayloadCase()) {
        case ORGANIZING: {
          mergeOrganizing(other.getOrganizing());
          break;
        }
        case ORGANIZING_LOGOUT: {
          mergeOrganizingLogout(other.getOrganizingLogout());
          break;
        }
        case ORGANIZING_FIND: {
          mergeOrganizingFind(other.getOrganizingFind());
          break;
        }
        case SAMPLE: {
          mergeSample(other.getSample());
          break;
        }
        case EMPTY: {
          playloadCase_ = 5;
          playload_ = other.playload_;
          onChanged();
          break;
        }
        case SAMPLE_FIND: {
          mergeSampleFind(other.getSampleFind());
          break;
        }
        case REGISTRATION: {
          mergeRegistration(other.getRegistration());
          break;
        }
        case CHILD: {
          mergeChild(other.getChild());
          break;
        }
        case CHILD_SAVED: {
          mergeChildSaved(other.getChildSaved());
          break;
        }
        case SAMPLES: {
          mergeSamples(other.getSamples());
          break;
        }
        case NEW: {
          mergeNew(other.getNew());
          break;
        }
        case PLAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getOrganizingFieldBuilder().getBuilder(),
                  extensionRegistry);
              playloadCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getOrganizingLogoutFieldBuilder().getBuilder(),
                  extensionRegistry);
              playloadCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getOrganizingFindFieldBuilder().getBuilder(),
                  extensionRegistry);
              playloadCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getSampleFieldBuilder().getBuilder(),
                  extensionRegistry);
              playloadCase_ = 4;
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              playloadCase_ = 5;
              playload_ = s;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getSampleFindFieldBuilder().getBuilder(),
                  extensionRegistry);
              playloadCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getRegistrationFieldBuilder().getBuilder(),
                  extensionRegistry);
              playloadCase_ = 7;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getChildFieldBuilder().getBuilder(),
                  extensionRegistry);
              playloadCase_ = 8;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getChildSavedFieldBuilder().getBuilder(),
                  extensionRegistry);
              playloadCase_ = 9;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  getNewFieldBuilder().getBuilder(),
                  extensionRegistry);
              playloadCase_ = 10;
              break;
            } // case 82
            case 90: {
              input.readMessage(
                  getSamplesFieldBuilder().getBuilder(),
                  extensionRegistry);
              playloadCase_ = 11;
              break;
            } // case 90
            case 96: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 96
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int playloadCase_ = 0;
    private java.lang.Object playload_;
    public PlayloadCase
        getPlayloadCase() {
      return PlayloadCase.forNumber(
          playloadCase_);
    }

    public Builder clearPlayload() {
      playloadCase_ = 0;
      playload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int type_ = 0;
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.CompetitionRequest.Type type = 12;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.CompetitionRequest.Type type = 12;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.CompetitionRequest.Type type = 12;</code>
     * @return The type.
     */
    @java.lang.Override
    public CompetitionRequest.Type getType() {
      CompetitionRequest.Type result = CompetitionRequest.Type.forNumber(type_);
      return result == null ? CompetitionRequest.Type.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.CompetitionRequest.Type type = 12;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(CompetitionRequest.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.CompetitionRequest.Type type = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder> organizingBuilder_;
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>.OrganizingDTO organizing = 1;</code>
     * @return Whether the organizing field is set.
     */
    @java.lang.Override
    public boolean hasOrganizing() {
      return playloadCase_ == 1;
    }
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>.OrganizingDTO organizing = 1;</code>
     * @return The organizing.
     */
    @java.lang.Override
    public OrganizingDTO getOrganizing() {
      if (organizingBuilder_ == null) {
        if (playloadCase_ == 1) {
          return (OrganizingDTO) playload_;
        }
        return OrganizingDTO.getDefaultInstance();
      } else {
        if (playloadCase_ == 1) {
          return organizingBuilder_.getMessage();
        }
        return OrganizingDTO.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>.OrganizingDTO organizing = 1;</code>
     */
    public Builder setOrganizing(OrganizingDTO value) {
      if (organizingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playload_ = value;
        onChanged();
      } else {
        organizingBuilder_.setMessage(value);
      }
      playloadCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>.OrganizingDTO organizing = 1;</code>
     */
    public Builder setOrganizing(
        OrganizingDTO.Builder builderForValue) {
      if (organizingBuilder_ == null) {
        playload_ = builderForValue.build();
        onChanged();
      } else {
        organizingBuilder_.setMessage(builderForValue.build());
      }
      playloadCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>.OrganizingDTO organizing = 1;</code>
     */
    public Builder mergeOrganizing(OrganizingDTO value) {
      if (organizingBuilder_ == null) {
        if (playloadCase_ == 1 &&
            playload_ != OrganizingDTO.getDefaultInstance()) {
          playload_ = OrganizingDTO.newBuilder((OrganizingDTO) playload_)
              .mergeFrom(value).buildPartial();
        } else {
          playload_ = value;
        }
        onChanged();
      } else {
        if (playloadCase_ == 1) {
          organizingBuilder_.mergeFrom(value);
        } else {
          organizingBuilder_.setMessage(value);
        }
      }
      playloadCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>.OrganizingDTO organizing = 1;</code>
     */
    public Builder clearOrganizing() {
      if (organizingBuilder_ == null) {
        if (playloadCase_ == 1) {
          playloadCase_ = 0;
          playload_ = null;
          onChanged();
        }
      } else {
        if (playloadCase_ == 1) {
          playloadCase_ = 0;
          playload_ = null;
        }
        organizingBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>.OrganizingDTO organizing = 1;</code>
     */
    public OrganizingDTO.Builder getOrganizingBuilder() {
      return getOrganizingFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>.OrganizingDTO organizing = 1;</code>
     */
    @java.lang.Override
    public OrganizingDTOOrBuilder getOrganizingOrBuilder() {
      if ((playloadCase_ == 1) && (organizingBuilder_ != null)) {
        return organizingBuilder_.getMessageOrBuilder();
      } else {
        if (playloadCase_ == 1) {
          return (OrganizingDTO) playload_;
        }
        return OrganizingDTO.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>.OrganizingDTO organizing = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder> 
        getOrganizingFieldBuilder() {
      if (organizingBuilder_ == null) {
        if (!(playloadCase_ == 1)) {
          playload_ = OrganizingDTO.getDefaultInstance();
        }
        organizingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder>(
                (OrganizingDTO) playload_,
                getParentForChildren(),
                isClean());
        playload_ = null;
      }
      playloadCase_ = 1;
      onChanged();
      return organizingBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder> organizingLogoutBuilder_;
    /**
     * <code>.OrganizingDTO organizing_logout = 2;</code>
     * @return Whether the organizingLogout field is set.
     */
    @java.lang.Override
    public boolean hasOrganizingLogout() {
      return playloadCase_ == 2;
    }
    /**
     * <code>.OrganizingDTO organizing_logout = 2;</code>
     * @return The organizingLogout.
     */
    @java.lang.Override
    public OrganizingDTO getOrganizingLogout() {
      if (organizingLogoutBuilder_ == null) {
        if (playloadCase_ == 2) {
          return (OrganizingDTO) playload_;
        }
        return OrganizingDTO.getDefaultInstance();
      } else {
        if (playloadCase_ == 2) {
          return organizingLogoutBuilder_.getMessage();
        }
        return OrganizingDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.OrganizingDTO organizing_logout = 2;</code>
     */
    public Builder setOrganizingLogout(OrganizingDTO value) {
      if (organizingLogoutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playload_ = value;
        onChanged();
      } else {
        organizingLogoutBuilder_.setMessage(value);
      }
      playloadCase_ = 2;
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_logout = 2;</code>
     */
    public Builder setOrganizingLogout(
        OrganizingDTO.Builder builderForValue) {
      if (organizingLogoutBuilder_ == null) {
        playload_ = builderForValue.build();
        onChanged();
      } else {
        organizingLogoutBuilder_.setMessage(builderForValue.build());
      }
      playloadCase_ = 2;
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_logout = 2;</code>
     */
    public Builder mergeOrganizingLogout(OrganizingDTO value) {
      if (organizingLogoutBuilder_ == null) {
        if (playloadCase_ == 2 &&
            playload_ != OrganizingDTO.getDefaultInstance()) {
          playload_ = OrganizingDTO.newBuilder((OrganizingDTO) playload_)
              .mergeFrom(value).buildPartial();
        } else {
          playload_ = value;
        }
        onChanged();
      } else {
        if (playloadCase_ == 2) {
          organizingLogoutBuilder_.mergeFrom(value);
        } else {
          organizingLogoutBuilder_.setMessage(value);
        }
      }
      playloadCase_ = 2;
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_logout = 2;</code>
     */
    public Builder clearOrganizingLogout() {
      if (organizingLogoutBuilder_ == null) {
        if (playloadCase_ == 2) {
          playloadCase_ = 0;
          playload_ = null;
          onChanged();
        }
      } else {
        if (playloadCase_ == 2) {
          playloadCase_ = 0;
          playload_ = null;
        }
        organizingLogoutBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_logout = 2;</code>
     */
    public OrganizingDTO.Builder getOrganizingLogoutBuilder() {
      return getOrganizingLogoutFieldBuilder().getBuilder();
    }
    /**
     * <code>.OrganizingDTO organizing_logout = 2;</code>
     */
    @java.lang.Override
    public OrganizingDTOOrBuilder getOrganizingLogoutOrBuilder() {
      if ((playloadCase_ == 2) && (organizingLogoutBuilder_ != null)) {
        return organizingLogoutBuilder_.getMessageOrBuilder();
      } else {
        if (playloadCase_ == 2) {
          return (OrganizingDTO) playload_;
        }
        return OrganizingDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.OrganizingDTO organizing_logout = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder> 
        getOrganizingLogoutFieldBuilder() {
      if (organizingLogoutBuilder_ == null) {
        if (!(playloadCase_ == 2)) {
          playload_ = OrganizingDTO.getDefaultInstance();
        }
        organizingLogoutBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder>(
                (OrganizingDTO) playload_,
                getParentForChildren(),
                isClean());
        playload_ = null;
      }
      playloadCase_ = 2;
      onChanged();
      return organizingLogoutBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder> organizingFindBuilder_;
    /**
     * <code>.OrganizingDTO organizing_find = 3;</code>
     * @return Whether the organizingFind field is set.
     */
    @java.lang.Override
    public boolean hasOrganizingFind() {
      return playloadCase_ == 3;
    }
    /**
     * <code>.OrganizingDTO organizing_find = 3;</code>
     * @return The organizingFind.
     */
    @java.lang.Override
    public OrganizingDTO getOrganizingFind() {
      if (organizingFindBuilder_ == null) {
        if (playloadCase_ == 3) {
          return (OrganizingDTO) playload_;
        }
        return OrganizingDTO.getDefaultInstance();
      } else {
        if (playloadCase_ == 3) {
          return organizingFindBuilder_.getMessage();
        }
        return OrganizingDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.OrganizingDTO organizing_find = 3;</code>
     */
    public Builder setOrganizingFind(OrganizingDTO value) {
      if (organizingFindBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playload_ = value;
        onChanged();
      } else {
        organizingFindBuilder_.setMessage(value);
      }
      playloadCase_ = 3;
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_find = 3;</code>
     */
    public Builder setOrganizingFind(
        OrganizingDTO.Builder builderForValue) {
      if (organizingFindBuilder_ == null) {
        playload_ = builderForValue.build();
        onChanged();
      } else {
        organizingFindBuilder_.setMessage(builderForValue.build());
      }
      playloadCase_ = 3;
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_find = 3;</code>
     */
    public Builder mergeOrganizingFind(OrganizingDTO value) {
      if (organizingFindBuilder_ == null) {
        if (playloadCase_ == 3 &&
            playload_ != OrganizingDTO.getDefaultInstance()) {
          playload_ = OrganizingDTO.newBuilder((OrganizingDTO) playload_)
              .mergeFrom(value).buildPartial();
        } else {
          playload_ = value;
        }
        onChanged();
      } else {
        if (playloadCase_ == 3) {
          organizingFindBuilder_.mergeFrom(value);
        } else {
          organizingFindBuilder_.setMessage(value);
        }
      }
      playloadCase_ = 3;
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_find = 3;</code>
     */
    public Builder clearOrganizingFind() {
      if (organizingFindBuilder_ == null) {
        if (playloadCase_ == 3) {
          playloadCase_ = 0;
          playload_ = null;
          onChanged();
        }
      } else {
        if (playloadCase_ == 3) {
          playloadCase_ = 0;
          playload_ = null;
        }
        organizingFindBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_find = 3;</code>
     */
    public OrganizingDTO.Builder getOrganizingFindBuilder() {
      return getOrganizingFindFieldBuilder().getBuilder();
    }
    /**
     * <code>.OrganizingDTO organizing_find = 3;</code>
     */
    @java.lang.Override
    public OrganizingDTOOrBuilder getOrganizingFindOrBuilder() {
      if ((playloadCase_ == 3) && (organizingFindBuilder_ != null)) {
        return organizingFindBuilder_.getMessageOrBuilder();
      } else {
        if (playloadCase_ == 3) {
          return (OrganizingDTO) playload_;
        }
        return OrganizingDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.OrganizingDTO organizing_find = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder> 
        getOrganizingFindFieldBuilder() {
      if (organizingFindBuilder_ == null) {
        if (!(playloadCase_ == 3)) {
          playload_ = OrganizingDTO.getDefaultInstance();
        }
        organizingFindBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder>(
                (OrganizingDTO) playload_,
                getParentForChildren(),
                isClean());
        playload_ = null;
      }
      playloadCase_ = 3;
      onChanged();
      return organizingFindBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder> sampleBuilder_;
    /**
     * <code>.SampleDTO sample = 4;</code>
     * @return Whether the sample field is set.
     */
    @java.lang.Override
    public boolean hasSample() {
      return playloadCase_ == 4;
    }
    /**
     * <code>.SampleDTO sample = 4;</code>
     * @return The sample.
     */
    @java.lang.Override
    public SampleDTO getSample() {
      if (sampleBuilder_ == null) {
        if (playloadCase_ == 4) {
          return (SampleDTO) playload_;
        }
        return SampleDTO.getDefaultInstance();
      } else {
        if (playloadCase_ == 4) {
          return sampleBuilder_.getMessage();
        }
        return SampleDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.SampleDTO sample = 4;</code>
     */
    public Builder setSample(SampleDTO value) {
      if (sampleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playload_ = value;
        onChanged();
      } else {
        sampleBuilder_.setMessage(value);
      }
      playloadCase_ = 4;
      return this;
    }
    /**
     * <code>.SampleDTO sample = 4;</code>
     */
    public Builder setSample(
        SampleDTO.Builder builderForValue) {
      if (sampleBuilder_ == null) {
        playload_ = builderForValue.build();
        onChanged();
      } else {
        sampleBuilder_.setMessage(builderForValue.build());
      }
      playloadCase_ = 4;
      return this;
    }
    /**
     * <code>.SampleDTO sample = 4;</code>
     */
    public Builder mergeSample(SampleDTO value) {
      if (sampleBuilder_ == null) {
        if (playloadCase_ == 4 &&
            playload_ != SampleDTO.getDefaultInstance()) {
          playload_ = SampleDTO.newBuilder((SampleDTO) playload_)
              .mergeFrom(value).buildPartial();
        } else {
          playload_ = value;
        }
        onChanged();
      } else {
        if (playloadCase_ == 4) {
          sampleBuilder_.mergeFrom(value);
        } else {
          sampleBuilder_.setMessage(value);
        }
      }
      playloadCase_ = 4;
      return this;
    }
    /**
     * <code>.SampleDTO sample = 4;</code>
     */
    public Builder clearSample() {
      if (sampleBuilder_ == null) {
        if (playloadCase_ == 4) {
          playloadCase_ = 0;
          playload_ = null;
          onChanged();
        }
      } else {
        if (playloadCase_ == 4) {
          playloadCase_ = 0;
          playload_ = null;
        }
        sampleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.SampleDTO sample = 4;</code>
     */
    public SampleDTO.Builder getSampleBuilder() {
      return getSampleFieldBuilder().getBuilder();
    }
    /**
     * <code>.SampleDTO sample = 4;</code>
     */
    @java.lang.Override
    public SampleDTOOrBuilder getSampleOrBuilder() {
      if ((playloadCase_ == 4) && (sampleBuilder_ != null)) {
        return sampleBuilder_.getMessageOrBuilder();
      } else {
        if (playloadCase_ == 4) {
          return (SampleDTO) playload_;
        }
        return SampleDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.SampleDTO sample = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder> 
        getSampleFieldBuilder() {
      if (sampleBuilder_ == null) {
        if (!(playloadCase_ == 4)) {
          playload_ = SampleDTO.getDefaultInstance();
        }
        sampleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder>(
                (SampleDTO) playload_,
                getParentForChildren(),
                isClean());
        playload_ = null;
      }
      playloadCase_ = 4;
      onChanged();
      return sampleBuilder_;
    }

    /**
     * <code>string empty = 5;</code>
     * @return Whether the empty field is set.
     */
    @java.lang.Override
    public boolean hasEmpty() {
      return playloadCase_ == 5;
    }
    /**
     * <code>string empty = 5;</code>
     * @return The empty.
     */
    @java.lang.Override
    public java.lang.String getEmpty() {
      java.lang.Object ref = "";
      if (playloadCase_ == 5) {
        ref = playload_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (playloadCase_ == 5) {
          playload_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string empty = 5;</code>
     * @return The bytes for empty.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmptyBytes() {
      java.lang.Object ref = "";
      if (playloadCase_ == 5) {
        ref = playload_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (playloadCase_ == 5) {
          playload_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string empty = 5;</code>
     * @param value The empty to set.
     * @return This builder for chaining.
     */
    public Builder setEmpty(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      playloadCase_ = 5;
      playload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string empty = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmpty() {
      if (playloadCase_ == 5) {
        playloadCase_ = 0;
        playload_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string empty = 5;</code>
     * @param value The bytes for empty to set.
     * @return This builder for chaining.
     */
    public Builder setEmptyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      playloadCase_ = 5;
      playload_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder> sampleFindBuilder_;
    /**
     * <code>.SampleDTO sample_find = 6;</code>
     * @return Whether the sampleFind field is set.
     */
    @java.lang.Override
    public boolean hasSampleFind() {
      return playloadCase_ == 6;
    }
    /**
     * <code>.SampleDTO sample_find = 6;</code>
     * @return The sampleFind.
     */
    @java.lang.Override
    public SampleDTO getSampleFind() {
      if (sampleFindBuilder_ == null) {
        if (playloadCase_ == 6) {
          return (SampleDTO) playload_;
        }
        return SampleDTO.getDefaultInstance();
      } else {
        if (playloadCase_ == 6) {
          return sampleFindBuilder_.getMessage();
        }
        return SampleDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.SampleDTO sample_find = 6;</code>
     */
    public Builder setSampleFind(SampleDTO value) {
      if (sampleFindBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playload_ = value;
        onChanged();
      } else {
        sampleFindBuilder_.setMessage(value);
      }
      playloadCase_ = 6;
      return this;
    }
    /**
     * <code>.SampleDTO sample_find = 6;</code>
     */
    public Builder setSampleFind(
        SampleDTO.Builder builderForValue) {
      if (sampleFindBuilder_ == null) {
        playload_ = builderForValue.build();
        onChanged();
      } else {
        sampleFindBuilder_.setMessage(builderForValue.build());
      }
      playloadCase_ = 6;
      return this;
    }
    /**
     * <code>.SampleDTO sample_find = 6;</code>
     */
    public Builder mergeSampleFind(SampleDTO value) {
      if (sampleFindBuilder_ == null) {
        if (playloadCase_ == 6 &&
            playload_ != SampleDTO.getDefaultInstance()) {
          playload_ = SampleDTO.newBuilder((SampleDTO) playload_)
              .mergeFrom(value).buildPartial();
        } else {
          playload_ = value;
        }
        onChanged();
      } else {
        if (playloadCase_ == 6) {
          sampleFindBuilder_.mergeFrom(value);
        } else {
          sampleFindBuilder_.setMessage(value);
        }
      }
      playloadCase_ = 6;
      return this;
    }
    /**
     * <code>.SampleDTO sample_find = 6;</code>
     */
    public Builder clearSampleFind() {
      if (sampleFindBuilder_ == null) {
        if (playloadCase_ == 6) {
          playloadCase_ = 0;
          playload_ = null;
          onChanged();
        }
      } else {
        if (playloadCase_ == 6) {
          playloadCase_ = 0;
          playload_ = null;
        }
        sampleFindBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.SampleDTO sample_find = 6;</code>
     */
    public SampleDTO.Builder getSampleFindBuilder() {
      return getSampleFindFieldBuilder().getBuilder();
    }
    /**
     * <code>.SampleDTO sample_find = 6;</code>
     */
    @java.lang.Override
    public SampleDTOOrBuilder getSampleFindOrBuilder() {
      if ((playloadCase_ == 6) && (sampleFindBuilder_ != null)) {
        return sampleFindBuilder_.getMessageOrBuilder();
      } else {
        if (playloadCase_ == 6) {
          return (SampleDTO) playload_;
        }
        return SampleDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.SampleDTO sample_find = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder> 
        getSampleFindFieldBuilder() {
      if (sampleFindBuilder_ == null) {
        if (!(playloadCase_ == 6)) {
          playload_ = SampleDTO.getDefaultInstance();
        }
        sampleFindBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder>(
                (SampleDTO) playload_,
                getParentForChildren(),
                isClean());
        playload_ = null;
      }
      playloadCase_ = 6;
      onChanged();
      return sampleFindBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        RegistrationDTO, RegistrationDTO.Builder, RegistrationDTOOrBuilder> registrationBuilder_;
    /**
     * <code>.RegistrationDTO registration = 7;</code>
     * @return Whether the registration field is set.
     */
    @java.lang.Override
    public boolean hasRegistration() {
      return playloadCase_ == 7;
    }
    /**
     * <code>.RegistrationDTO registration = 7;</code>
     * @return The registration.
     */
    @java.lang.Override
    public RegistrationDTO getRegistration() {
      if (registrationBuilder_ == null) {
        if (playloadCase_ == 7) {
          return (RegistrationDTO) playload_;
        }
        return RegistrationDTO.getDefaultInstance();
      } else {
        if (playloadCase_ == 7) {
          return registrationBuilder_.getMessage();
        }
        return RegistrationDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.RegistrationDTO registration = 7;</code>
     */
    public Builder setRegistration(RegistrationDTO value) {
      if (registrationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playload_ = value;
        onChanged();
      } else {
        registrationBuilder_.setMessage(value);
      }
      playloadCase_ = 7;
      return this;
    }
    /**
     * <code>.RegistrationDTO registration = 7;</code>
     */
    public Builder setRegistration(
        RegistrationDTO.Builder builderForValue) {
      if (registrationBuilder_ == null) {
        playload_ = builderForValue.build();
        onChanged();
      } else {
        registrationBuilder_.setMessage(builderForValue.build());
      }
      playloadCase_ = 7;
      return this;
    }
    /**
     * <code>.RegistrationDTO registration = 7;</code>
     */
    public Builder mergeRegistration(RegistrationDTO value) {
      if (registrationBuilder_ == null) {
        if (playloadCase_ == 7 &&
            playload_ != RegistrationDTO.getDefaultInstance()) {
          playload_ = RegistrationDTO.newBuilder((RegistrationDTO) playload_)
              .mergeFrom(value).buildPartial();
        } else {
          playload_ = value;
        }
        onChanged();
      } else {
        if (playloadCase_ == 7) {
          registrationBuilder_.mergeFrom(value);
        } else {
          registrationBuilder_.setMessage(value);
        }
      }
      playloadCase_ = 7;
      return this;
    }
    /**
     * <code>.RegistrationDTO registration = 7;</code>
     */
    public Builder clearRegistration() {
      if (registrationBuilder_ == null) {
        if (playloadCase_ == 7) {
          playloadCase_ = 0;
          playload_ = null;
          onChanged();
        }
      } else {
        if (playloadCase_ == 7) {
          playloadCase_ = 0;
          playload_ = null;
        }
        registrationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.RegistrationDTO registration = 7;</code>
     */
    public RegistrationDTO.Builder getRegistrationBuilder() {
      return getRegistrationFieldBuilder().getBuilder();
    }
    /**
     * <code>.RegistrationDTO registration = 7;</code>
     */
    @java.lang.Override
    public RegistrationDTOOrBuilder getRegistrationOrBuilder() {
      if ((playloadCase_ == 7) && (registrationBuilder_ != null)) {
        return registrationBuilder_.getMessageOrBuilder();
      } else {
        if (playloadCase_ == 7) {
          return (RegistrationDTO) playload_;
        }
        return RegistrationDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.RegistrationDTO registration = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        RegistrationDTO, RegistrationDTO.Builder, RegistrationDTOOrBuilder> 
        getRegistrationFieldBuilder() {
      if (registrationBuilder_ == null) {
        if (!(playloadCase_ == 7)) {
          playload_ = RegistrationDTO.getDefaultInstance();
        }
        registrationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            RegistrationDTO, RegistrationDTO.Builder, RegistrationDTOOrBuilder>(
                (RegistrationDTO) playload_,
                getParentForChildren(),
                isClean());
        playload_ = null;
      }
      playloadCase_ = 7;
      onChanged();
      return registrationBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder> childBuilder_;
    /**
     * <code>.ChildDTO child = 8;</code>
     * @return Whether the child field is set.
     */
    @java.lang.Override
    public boolean hasChild() {
      return playloadCase_ == 8;
    }
    /**
     * <code>.ChildDTO child = 8;</code>
     * @return The child.
     */
    @java.lang.Override
    public ChildDTO getChild() {
      if (childBuilder_ == null) {
        if (playloadCase_ == 8) {
          return (ChildDTO) playload_;
        }
        return ChildDTO.getDefaultInstance();
      } else {
        if (playloadCase_ == 8) {
          return childBuilder_.getMessage();
        }
        return ChildDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.ChildDTO child = 8;</code>
     */
    public Builder setChild(ChildDTO value) {
      if (childBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playload_ = value;
        onChanged();
      } else {
        childBuilder_.setMessage(value);
      }
      playloadCase_ = 8;
      return this;
    }
    /**
     * <code>.ChildDTO child = 8;</code>
     */
    public Builder setChild(
        ChildDTO.Builder builderForValue) {
      if (childBuilder_ == null) {
        playload_ = builderForValue.build();
        onChanged();
      } else {
        childBuilder_.setMessage(builderForValue.build());
      }
      playloadCase_ = 8;
      return this;
    }
    /**
     * <code>.ChildDTO child = 8;</code>
     */
    public Builder mergeChild(ChildDTO value) {
      if (childBuilder_ == null) {
        if (playloadCase_ == 8 &&
            playload_ != ChildDTO.getDefaultInstance()) {
          playload_ = ChildDTO.newBuilder((ChildDTO) playload_)
              .mergeFrom(value).buildPartial();
        } else {
          playload_ = value;
        }
        onChanged();
      } else {
        if (playloadCase_ == 8) {
          childBuilder_.mergeFrom(value);
        } else {
          childBuilder_.setMessage(value);
        }
      }
      playloadCase_ = 8;
      return this;
    }
    /**
     * <code>.ChildDTO child = 8;</code>
     */
    public Builder clearChild() {
      if (childBuilder_ == null) {
        if (playloadCase_ == 8) {
          playloadCase_ = 0;
          playload_ = null;
          onChanged();
        }
      } else {
        if (playloadCase_ == 8) {
          playloadCase_ = 0;
          playload_ = null;
        }
        childBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ChildDTO child = 8;</code>
     */
    public ChildDTO.Builder getChildBuilder() {
      return getChildFieldBuilder().getBuilder();
    }
    /**
     * <code>.ChildDTO child = 8;</code>
     */
    @java.lang.Override
    public ChildDTOOrBuilder getChildOrBuilder() {
      if ((playloadCase_ == 8) && (childBuilder_ != null)) {
        return childBuilder_.getMessageOrBuilder();
      } else {
        if (playloadCase_ == 8) {
          return (ChildDTO) playload_;
        }
        return ChildDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.ChildDTO child = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder> 
        getChildFieldBuilder() {
      if (childBuilder_ == null) {
        if (!(playloadCase_ == 8)) {
          playload_ = ChildDTO.getDefaultInstance();
        }
        childBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder>(
                (ChildDTO) playload_,
                getParentForChildren(),
                isClean());
        playload_ = null;
      }
      playloadCase_ = 8;
      onChanged();
      return childBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder> childSavedBuilder_;
    /**
     * <code>.ChildDTO child_saved = 9;</code>
     * @return Whether the childSaved field is set.
     */
    @java.lang.Override
    public boolean hasChildSaved() {
      return playloadCase_ == 9;
    }
    /**
     * <code>.ChildDTO child_saved = 9;</code>
     * @return The childSaved.
     */
    @java.lang.Override
    public ChildDTO getChildSaved() {
      if (childSavedBuilder_ == null) {
        if (playloadCase_ == 9) {
          return (ChildDTO) playload_;
        }
        return ChildDTO.getDefaultInstance();
      } else {
        if (playloadCase_ == 9) {
          return childSavedBuilder_.getMessage();
        }
        return ChildDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.ChildDTO child_saved = 9;</code>
     */
    public Builder setChildSaved(ChildDTO value) {
      if (childSavedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playload_ = value;
        onChanged();
      } else {
        childSavedBuilder_.setMessage(value);
      }
      playloadCase_ = 9;
      return this;
    }
    /**
     * <code>.ChildDTO child_saved = 9;</code>
     */
    public Builder setChildSaved(
        ChildDTO.Builder builderForValue) {
      if (childSavedBuilder_ == null) {
        playload_ = builderForValue.build();
        onChanged();
      } else {
        childSavedBuilder_.setMessage(builderForValue.build());
      }
      playloadCase_ = 9;
      return this;
    }
    /**
     * <code>.ChildDTO child_saved = 9;</code>
     */
    public Builder mergeChildSaved(ChildDTO value) {
      if (childSavedBuilder_ == null) {
        if (playloadCase_ == 9 &&
            playload_ != ChildDTO.getDefaultInstance()) {
          playload_ = ChildDTO.newBuilder((ChildDTO) playload_)
              .mergeFrom(value).buildPartial();
        } else {
          playload_ = value;
        }
        onChanged();
      } else {
        if (playloadCase_ == 9) {
          childSavedBuilder_.mergeFrom(value);
        } else {
          childSavedBuilder_.setMessage(value);
        }
      }
      playloadCase_ = 9;
      return this;
    }
    /**
     * <code>.ChildDTO child_saved = 9;</code>
     */
    public Builder clearChildSaved() {
      if (childSavedBuilder_ == null) {
        if (playloadCase_ == 9) {
          playloadCase_ = 0;
          playload_ = null;
          onChanged();
        }
      } else {
        if (playloadCase_ == 9) {
          playloadCase_ = 0;
          playload_ = null;
        }
        childSavedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ChildDTO child_saved = 9;</code>
     */
    public ChildDTO.Builder getChildSavedBuilder() {
      return getChildSavedFieldBuilder().getBuilder();
    }
    /**
     * <code>.ChildDTO child_saved = 9;</code>
     */
    @java.lang.Override
    public ChildDTOOrBuilder getChildSavedOrBuilder() {
      if ((playloadCase_ == 9) && (childSavedBuilder_ != null)) {
        return childSavedBuilder_.getMessageOrBuilder();
      } else {
        if (playloadCase_ == 9) {
          return (ChildDTO) playload_;
        }
        return ChildDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.ChildDTO child_saved = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder> 
        getChildSavedFieldBuilder() {
      if (childSavedBuilder_ == null) {
        if (!(playloadCase_ == 9)) {
          playload_ = ChildDTO.getDefaultInstance();
        }
        childSavedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder>(
                (ChildDTO) playload_,
                getParentForChildren(),
                isClean());
        playload_ = null;
      }
      playloadCase_ = 9;
      onChanged();
      return childSavedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder> samplesBuilder_;
    /**
     * <code>.SampleDTO samples = 11;</code>
     * @return Whether the samples field is set.
     */
    @java.lang.Override
    public boolean hasSamples() {
      return playloadCase_ == 11;
    }
    /**
     * <code>.SampleDTO samples = 11;</code>
     * @return The samples.
     */
    @java.lang.Override
    public SampleDTO getSamples() {
      if (samplesBuilder_ == null) {
        if (playloadCase_ == 11) {
          return (SampleDTO) playload_;
        }
        return SampleDTO.getDefaultInstance();
      } else {
        if (playloadCase_ == 11) {
          return samplesBuilder_.getMessage();
        }
        return SampleDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.SampleDTO samples = 11;</code>
     */
    public Builder setSamples(SampleDTO value) {
      if (samplesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playload_ = value;
        onChanged();
      } else {
        samplesBuilder_.setMessage(value);
      }
      playloadCase_ = 11;
      return this;
    }
    /**
     * <code>.SampleDTO samples = 11;</code>
     */
    public Builder setSamples(
        SampleDTO.Builder builderForValue) {
      if (samplesBuilder_ == null) {
        playload_ = builderForValue.build();
        onChanged();
      } else {
        samplesBuilder_.setMessage(builderForValue.build());
      }
      playloadCase_ = 11;
      return this;
    }
    /**
     * <code>.SampleDTO samples = 11;</code>
     */
    public Builder mergeSamples(SampleDTO value) {
      if (samplesBuilder_ == null) {
        if (playloadCase_ == 11 &&
            playload_ != SampleDTO.getDefaultInstance()) {
          playload_ = SampleDTO.newBuilder((SampleDTO) playload_)
              .mergeFrom(value).buildPartial();
        } else {
          playload_ = value;
        }
        onChanged();
      } else {
        if (playloadCase_ == 11) {
          samplesBuilder_.mergeFrom(value);
        } else {
          samplesBuilder_.setMessage(value);
        }
      }
      playloadCase_ = 11;
      return this;
    }
    /**
     * <code>.SampleDTO samples = 11;</code>
     */
    public Builder clearSamples() {
      if (samplesBuilder_ == null) {
        if (playloadCase_ == 11) {
          playloadCase_ = 0;
          playload_ = null;
          onChanged();
        }
      } else {
        if (playloadCase_ == 11) {
          playloadCase_ = 0;
          playload_ = null;
        }
        samplesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.SampleDTO samples = 11;</code>
     */
    public SampleDTO.Builder getSamplesBuilder() {
      return getSamplesFieldBuilder().getBuilder();
    }
    /**
     * <code>.SampleDTO samples = 11;</code>
     */
    @java.lang.Override
    public SampleDTOOrBuilder getSamplesOrBuilder() {
      if ((playloadCase_ == 11) && (samplesBuilder_ != null)) {
        return samplesBuilder_.getMessageOrBuilder();
      } else {
        if (playloadCase_ == 11) {
          return (SampleDTO) playload_;
        }
        return SampleDTO.getDefaultInstance();
      }
    }
    /**
     * <code>.SampleDTO samples = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder> 
        getSamplesFieldBuilder() {
      if (samplesBuilder_ == null) {
        if (!(playloadCase_ == 11)) {
          playload_ = SampleDTO.getDefaultInstance();
        }
        samplesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder>(
                (SampleDTO) playload_,
                getParentForChildren(),
                isClean());
        playload_ = null;
      }
      playloadCase_ = 11;
      onChanged();
      return samplesBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        New, New.Builder, NewOrBuilder> newBuilder_;
    /**
     * <code>.New new = 10;</code>
     * @return Whether the new field is set.
     */
    @java.lang.Override
    public boolean hasNew() {
      return playloadCase_ == 10;
    }
    /**
     * <code>.New new = 10;</code>
     * @return The new.
     */
    @java.lang.Override
    public New getNew() {
      if (newBuilder_ == null) {
        if (playloadCase_ == 10) {
          return (New) playload_;
        }
        return New.getDefaultInstance();
      } else {
        if (playloadCase_ == 10) {
          return newBuilder_.getMessage();
        }
        return New.getDefaultInstance();
      }
    }
    /**
     * <code>.New new = 10;</code>
     */
    public Builder setNew(New value) {
      if (newBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playload_ = value;
        onChanged();
      } else {
        newBuilder_.setMessage(value);
      }
      playloadCase_ = 10;
      return this;
    }
    /**
     * <code>.New new = 10;</code>
     */
    public Builder setNew(
        New.Builder builderForValue) {
      if (newBuilder_ == null) {
        playload_ = builderForValue.build();
        onChanged();
      } else {
        newBuilder_.setMessage(builderForValue.build());
      }
      playloadCase_ = 10;
      return this;
    }
    /**
     * <code>.New new = 10;</code>
     */
    public Builder mergeNew(New value) {
      if (newBuilder_ == null) {
        if (playloadCase_ == 10 &&
            playload_ != New.getDefaultInstance()) {
          playload_ = New.newBuilder((New) playload_)
              .mergeFrom(value).buildPartial();
        } else {
          playload_ = value;
        }
        onChanged();
      } else {
        if (playloadCase_ == 10) {
          newBuilder_.mergeFrom(value);
        } else {
          newBuilder_.setMessage(value);
        }
      }
      playloadCase_ = 10;
      return this;
    }
    /**
     * <code>.New new = 10;</code>
     */
    public Builder clearNew() {
      if (newBuilder_ == null) {
        if (playloadCase_ == 10) {
          playloadCase_ = 0;
          playload_ = null;
          onChanged();
        }
      } else {
        if (playloadCase_ == 10) {
          playloadCase_ = 0;
          playload_ = null;
        }
        newBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.New new = 10;</code>
     */
    public New.Builder getNewBuilder() {
      return getNewFieldBuilder().getBuilder();
    }
    /**
     * <code>.New new = 10;</code>
     */
    @java.lang.Override
    public NewOrBuilder getNewOrBuilder() {
      if ((playloadCase_ == 10) && (newBuilder_ != null)) {
        return newBuilder_.getMessageOrBuilder();
      } else {
        if (playloadCase_ == 10) {
          return (New) playload_;
        }
        return New.getDefaultInstance();
      }
    }
    /**
     * <code>.New new = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        New, New.Builder, NewOrBuilder> 
        getNewFieldBuilder() {
      if (newBuilder_ == null) {
        if (!(playloadCase_ == 10)) {
          playload_ = New.getDefaultInstance();
        }
        newBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            New, New.Builder, NewOrBuilder>(
                (New) playload_,
                getParentForChildren(),
                isClean());
        playload_ = null;
      }
      playloadCase_ = 10;
      onChanged();
      return newBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:CompetitionRequest)
  }

  // @@protoc_insertion_point(class_scope:CompetitionRequest)
  private static final CompetitionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CompetitionRequest();
  }

  public static CompetitionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompetitionRequest>
      PARSER = new com.google.protobuf.AbstractParser<CompetitionRequest>() {
    @java.lang.Override
    public CompetitionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CompetitionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompetitionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CompetitionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

