// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: competition.proto
package org.example.javaFiles;
// Protobuf Java Version: 4.26.1
public interface CompetitionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CompetitionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Identifies which request is filled in.
   * </pre>
   *
   * <code>.CompetitionRequest.Type type = 12;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Identifies which request is filled in.
   * </pre>
   *
   * <code>.CompetitionRequest.Type type = 12;</code>
   * @return The type.
   */
  CompetitionRequest.Type getType();

  /**
   * <pre>
   * One of the following will be filled in, depending on the type.
   * </pre>
   *
   * <code>.OrganizingDTO organizing = 1;</code>
   * @return Whether the organizing field is set.
   */
  boolean hasOrganizing();
  /**
   * <pre>
   * One of the following will be filled in, depending on the type.
   * </pre>
   *
   * <code>.OrganizingDTO organizing = 1;</code>
   * @return The organizing.
   */
  OrganizingDTO getOrganizing();
  /**
   * <pre>
   * One of the following will be filled in, depending on the type.
   * </pre>
   *
   * <code>.OrganizingDTO organizing = 1;</code>
   */
  OrganizingDTOOrBuilder getOrganizingOrBuilder();

  /**
   * <code>.OrganizingDTO organizing_logout = 2;</code>
   * @return Whether the organizingLogout field is set.
   */
  boolean hasOrganizingLogout();
  /**
   * <code>.OrganizingDTO organizing_logout = 2;</code>
   * @return The organizingLogout.
   */
  OrganizingDTO getOrganizingLogout();
  /**
   * <code>.OrganizingDTO organizing_logout = 2;</code>
   */
  OrganizingDTOOrBuilder getOrganizingLogoutOrBuilder();

  /**
   * <code>.OrganizingDTO organizing_find = 3;</code>
   * @return Whether the organizingFind field is set.
   */
  boolean hasOrganizingFind();
  /**
   * <code>.OrganizingDTO organizing_find = 3;</code>
   * @return The organizingFind.
   */
  OrganizingDTO getOrganizingFind();
  /**
   * <code>.OrganizingDTO organizing_find = 3;</code>
   */
  OrganizingDTOOrBuilder getOrganizingFindOrBuilder();

  /**
   * <code>.SampleDTO sample = 4;</code>
   * @return Whether the sample field is set.
   */
  boolean hasSample();
  /**
   * <code>.SampleDTO sample = 4;</code>
   * @return The sample.
   */
  SampleDTO getSample();
  /**
   * <code>.SampleDTO sample = 4;</code>
   */
  SampleDTOOrBuilder getSampleOrBuilder();

  /**
   * <code>string empty = 5;</code>
   * @return Whether the empty field is set.
   */
  boolean hasEmpty();
  /**
   * <code>string empty = 5;</code>
   * @return The empty.
   */
  java.lang.String getEmpty();
  /**
   * <code>string empty = 5;</code>
   * @return The bytes for empty.
   */
  com.google.protobuf.ByteString
      getEmptyBytes();

  /**
   * <code>.SampleDTO sample_find = 6;</code>
   * @return Whether the sampleFind field is set.
   */
  boolean hasSampleFind();
  /**
   * <code>.SampleDTO sample_find = 6;</code>
   * @return The sampleFind.
   */
  SampleDTO getSampleFind();
  /**
   * <code>.SampleDTO sample_find = 6;</code>
   */
  SampleDTOOrBuilder getSampleFindOrBuilder();

  /**
   * <code>.RegistrationDTO registration = 7;</code>
   * @return Whether the registration field is set.
   */
  boolean hasRegistration();
  /**
   * <code>.RegistrationDTO registration = 7;</code>
   * @return The registration.
   */
  RegistrationDTO getRegistration();
  /**
   * <code>.RegistrationDTO registration = 7;</code>
   */
  RegistrationDTOOrBuilder getRegistrationOrBuilder();

  /**
   * <code>.ChildDTO child = 8;</code>
   * @return Whether the child field is set.
   */
  boolean hasChild();
  /**
   * <code>.ChildDTO child = 8;</code>
   * @return The child.
   */
  ChildDTO getChild();
  /**
   * <code>.ChildDTO child = 8;</code>
   */
  ChildDTOOrBuilder getChildOrBuilder();

  /**
   * <code>.ChildDTO child_saved = 9;</code>
   * @return Whether the childSaved field is set.
   */
  boolean hasChildSaved();
  /**
   * <code>.ChildDTO child_saved = 9;</code>
   * @return The childSaved.
   */
  ChildDTO getChildSaved();
  /**
   * <code>.ChildDTO child_saved = 9;</code>
   */
  ChildDTOOrBuilder getChildSavedOrBuilder();

  /**
   * <code>.SampleDTO samples = 11;</code>
   * @return Whether the samples field is set.
   */
  boolean hasSamples();
  /**
   * <code>.SampleDTO samples = 11;</code>
   * @return The samples.
   */
  SampleDTO getSamples();
  /**
   * <code>.SampleDTO samples = 11;</code>
   */
  SampleDTOOrBuilder getSamplesOrBuilder();

  /**
   * <code>.New new = 10;</code>
   * @return Whether the new field is set.
   */
  boolean hasNew();
  /**
   * <code>.New new = 10;</code>
   * @return The new.
   */
  New getNew();
  /**
   * <code>.New new = 10;</code>
   */
  NewOrBuilder getNewOrBuilder();

  CompetitionRequest.PlayloadCase getPlayloadCase();
}
