// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: competition.proto
// Protobuf Java Version: 4.26.1
package org.example.javaFiles;
public final class CompetitionProtobuf {
  private CompetitionProtobuf() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
            CompetitionProtobuf.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CompetitionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CompetitionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CompetitionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CompetitionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SampleDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistrationDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RegistrationDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChildDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChildDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrganizingDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OrganizingDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_New_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_New_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021competition.proto\"\256\005\n\022CompetitionReque" +
      "st\022&\n\004type\030\014 \001(\0162\030.CompetitionRequest.Ty" +
      "pe\022$\n\norganizing\030\001 \001(\0132\016.OrganizingDTOH\000" +
      "\022+\n\021organizing_logout\030\002 \001(\0132\016.Organizing" +
      "DTOH\000\022)\n\017organizing_find\030\003 \001(\0132\016.Organiz" +
      "ingDTOH\000\022\034\n\006sample\030\004 \001(\0132\n.SampleDTOH\000\022\017" +
      "\n\005empty\030\005 \001(\tH\000\022!\n\013sample_find\030\006 \001(\0132\n.S" +
      "ampleDTOH\000\022(\n\014registration\030\007 \001(\0132\020.Regis" +
      "trationDTOH\000\022\032\n\005child\030\010 \001(\0132\t.ChildDTOH\000" +
      "\022 \n\013child_saved\030\t \001(\0132\t.ChildDTOH\000\022\035\n\007sa" +
      "mples\030\013 \001(\0132\n.SampleDTOH\000\022\023\n\003new\030\n \001(\0132\004" +
      ".NewH\000\"\367\001\n\004Type\022\013\n\007Unknown\020\000\022\t\n\005LOGIN\020\001\022" +
      "\n\n\006LOGOUT\020\002\022\023\n\017FIND_ORGANIZING\020\003\022!\n\035NUMB" +
      "ER_OF_CHILDREN_FOR_SAMPLE\020\004\022\024\n\020FIND_ALL_" +
      "SAMPLES\020\005\022\017\n\013FIND_SAMPLE\020\006\022\022\n\016REGISTER_C" +
      "HILD\020\007\022\016\n\nFIND_CHILD\020\010\022\016\n\nSAVE_CHILD\020\t\022\007" +
      "\n\003NEW\020\n\022\034\n\030LIST_CHILDREN_FOR_SAMPLE\020\013\022\006\n" +
      "\002OK\020\014\022\t\n\005ERROR\020\rB\n\n\010playload\"\335\006\n\023Competi" +
      "tionResponse\0229\n\rtype_Response\030\002 \001(\0162\".Co" +
      "mpetitionResponse.Type_Response\022&\n\014regis" +
      "tration\030\003 \001(\0132\020.RegistrationDTO\022\r\n\005error" +
      "\030\016 \001(\t\022\'\n\017organizing_resp\030\001 \001(\0132\016.Organi" +
      "zingDTO\022(\n\020organizing_resp2\030\004 \001(\0132\016.Orga" +
      "nizingDTO\022\037\n\013samples_res\030\005 \003(\0132\n.SampleD" +
      "TO\022\"\n\norganizing\030\006 \001(\0132\016.OrganizingDTO\022\032" +
      "\n\006sample\030\007 \001(\0132\n.SampleDTO\022\033\n\010children\030\010" +
      " \003(\0132\t.ChildDTO\022\030\n\005child\030\t \001(\0132\t.ChildDT" +
      "O\022\021\n\003new\030\014 \001(\0132\004.New\022\036\n\013child_saved\030\n \001(" +
      "\0132\t.ChildDTO\022\016\n\006number\030\r \001(\t\"\245\003\n\rType_Re" +
      "sponse\022\024\n\020Unknown_Response\020\000\022!\n\035ORGANIZI" +
      "NG_LOGGED_IN_Response\020\001\022\017\n\013OK_Response\020\002" +
      "\022\022\n\016REGISTER_CHILD\020\003\022\"\n\036ORGANIZING_LOGGE" +
      "D_OUT_Response\020\004\022\035\n\031FIND_ALL_SAMPLES_Res" +
      "ponse\020\005\022\034\n\030FIND_ORGANIZING_Response\020\006\022\030\n" +
      "\024FIND_SAMPLE_Response\020\007\022\032\n\026LIST_CHILDREN" +
      "_Response\020\010\022\027\n\023FIND_CHILD_Response\020\t\022\027\n\023" +
      "SAVE_CHILD_Response\020\n\022\033\n\027REGISTER_CHILD_" +
      "Response\020\013\022\020\n\014NEW_Response\020\014\022*\n&NUMBER_O" +
      "F_CHILDREN_FOR_SAMPLE_Response\020\r\022\022\n\016ERRO" +
      "R_Response\020\016\"D\n\tSampleDTO\022\n\n\002id\030\001 \001(\t\022\026\n" +
      "\016sampleCategory\030\002 \001(\t\022\023\n\013ageCategory\030\003 \001" +
      "(\t\"a\n\017RegistrationDTO\022\017\n\007childId\030\001 \001(\t\022\020" +
      "\n\010sampleId\030\002 \001(\t\022\026\n\016sampleCategory\030\003 \001(\t" +
      "\022\023\n\013ageCategory\030\004 \001(\t\"A\n\010ChildDTO\022\n\n\002id\030" +
      "\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(\t\022\016\n\006numb" +
      "er\030\004 \001(\t\"M\n\rOrganizingDTO\022\n\n\002id\030\001 \001(\t\022\020\n" +
      "\010username\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\014\n\004nam" +
      "e\030\004 \001(\t\"\'\n\003New\022\020\n\010sampleId\030\001 \001(\t\022\016\n\006numb" +
      "er\030\002 \001(\tB=B\"serverClientGrpc.protobuffpr" +
      "otocolP\001\242\002\024CompetitionProtobufsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CompetitionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CompetitionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CompetitionRequest_descriptor,
        new java.lang.String[] { "Type", "Organizing", "OrganizingLogout", "OrganizingFind", "Sample", "Empty", "SampleFind", "Registration", "Child", "ChildSaved", "Samples", "New", "Playload", });
    internal_static_CompetitionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CompetitionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CompetitionResponse_descriptor,
        new java.lang.String[] { "TypeResponse", "Registration", "Error", "OrganizingResp", "OrganizingResp2", "SamplesRes", "Organizing", "Sample", "Children", "Child", "New", "ChildSaved", "Number", });
    internal_static_SampleDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SampleDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SampleDTO_descriptor,
        new java.lang.String[] { "Id", "SampleCategory", "AgeCategory", });
    internal_static_RegistrationDTO_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RegistrationDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RegistrationDTO_descriptor,
        new java.lang.String[] { "ChildId", "SampleId", "SampleCategory", "AgeCategory", });
    internal_static_ChildDTO_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ChildDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ChildDTO_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Number", });
    internal_static_OrganizingDTO_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_OrganizingDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OrganizingDTO_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", "Name", });
    internal_static_New_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_New_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_New_descriptor,
        new java.lang.String[] { "SampleId", "Number", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
