// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: competition.proto

// Protobuf Java Version: 4.26.1
/**
 * Protobuf type {@code CompetitionResponse}
 */package org.example.javaFiles;
public final class CompetitionResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:CompetitionResponse)
    CompetitionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      CompetitionResponse.class.getName());
  }
  // Use CompetitionResponse.newBuilder() to construct.
  private CompetitionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CompetitionResponse() {
    typeResponse_ = 0;
    error_ = "";
    samplesRes_ = java.util.Collections.emptyList();
    children_ = java.util.Collections.emptyList();
    number_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CompetitionProtobuf.internal_static_CompetitionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CompetitionProtobuf.internal_static_CompetitionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CompetitionResponse.class, CompetitionResponse.Builder.class);
  }

  /**
   * Protobuf enum {@code CompetitionResponse.Type_Response}
   */
  public enum Type_Response
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unknown_Response = 0;</code>
     */
    Unknown_Response(0),
    /**
     * <code>ORGANIZING_LOGGED_IN_Response = 1;</code>
     */
    ORGANIZING_LOGGED_IN_Response(1),
    /**
     * <code>OK_Response = 2;</code>
     */
    OK_Response(2),
    /**
     * <code>REGISTER_CHILD = 3;</code>
     */
    REGISTER_CHILD(3),
    /**
     * <code>ORGANIZING_LOGGED_OUT_Response = 4;</code>
     */
    ORGANIZING_LOGGED_OUT_Response(4),
    /**
     * <code>FIND_ALL_SAMPLES_Response = 5;</code>
     */
    FIND_ALL_SAMPLES_Response(5),
    /**
     * <code>FIND_ORGANIZING_Response = 6;</code>
     */
    FIND_ORGANIZING_Response(6),
    /**
     * <code>FIND_SAMPLE_Response = 7;</code>
     */
    FIND_SAMPLE_Response(7),
    /**
     * <code>LIST_CHILDREN_Response = 8;</code>
     */
    LIST_CHILDREN_Response(8),
    /**
     * <code>FIND_CHILD_Response = 9;</code>
     */
    FIND_CHILD_Response(9),
    /**
     * <code>SAVE_CHILD_Response = 10;</code>
     */
    SAVE_CHILD_Response(10),
    /**
     * <code>REGISTER_CHILD_Response = 11;</code>
     */
    REGISTER_CHILD_Response(11),
    /**
     * <code>NEW_Response = 12;</code>
     */
    NEW_Response(12),
    /**
     * <code>NUMBER_OF_CHILDREN_FOR_SAMPLE_Response = 13;</code>
     */
    NUMBER_OF_CHILDREN_FOR_SAMPLE_Response(13),
    /**
     * <code>ERROR_Response = 14;</code>
     */
    ERROR_Response(14),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Type_Response.class.getName());
    }
    /**
     * <code>Unknown_Response = 0;</code>
     */
    public static final int Unknown_Response_VALUE = 0;
    /**
     * <code>ORGANIZING_LOGGED_IN_Response = 1;</code>
     */
    public static final int ORGANIZING_LOGGED_IN_Response_VALUE = 1;
    /**
     * <code>OK_Response = 2;</code>
     */
    public static final int OK_Response_VALUE = 2;
    /**
     * <code>REGISTER_CHILD = 3;</code>
     */
    public static final int REGISTER_CHILD_VALUE = 3;
    /**
     * <code>ORGANIZING_LOGGED_OUT_Response = 4;</code>
     */
    public static final int ORGANIZING_LOGGED_OUT_Response_VALUE = 4;
    /**
     * <code>FIND_ALL_SAMPLES_Response = 5;</code>
     */
    public static final int FIND_ALL_SAMPLES_Response_VALUE = 5;
    /**
     * <code>FIND_ORGANIZING_Response = 6;</code>
     */
    public static final int FIND_ORGANIZING_Response_VALUE = 6;
    /**
     * <code>FIND_SAMPLE_Response = 7;</code>
     */
    public static final int FIND_SAMPLE_Response_VALUE = 7;
    /**
     * <code>LIST_CHILDREN_Response = 8;</code>
     */
    public static final int LIST_CHILDREN_Response_VALUE = 8;
    /**
     * <code>FIND_CHILD_Response = 9;</code>
     */
    public static final int FIND_CHILD_Response_VALUE = 9;
    /**
     * <code>SAVE_CHILD_Response = 10;</code>
     */
    public static final int SAVE_CHILD_Response_VALUE = 10;
    /**
     * <code>REGISTER_CHILD_Response = 11;</code>
     */
    public static final int REGISTER_CHILD_Response_VALUE = 11;
    /**
     * <code>NEW_Response = 12;</code>
     */
    public static final int NEW_Response_VALUE = 12;
    /**
     * <code>NUMBER_OF_CHILDREN_FOR_SAMPLE_Response = 13;</code>
     */
    public static final int NUMBER_OF_CHILDREN_FOR_SAMPLE_Response_VALUE = 13;
    /**
     * <code>ERROR_Response = 14;</code>
     */
    public static final int ERROR_Response_VALUE = 14;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type_Response valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type_Response forNumber(int value) {
      switch (value) {
        case 0: return Unknown_Response;
        case 1: return ORGANIZING_LOGGED_IN_Response;
        case 2: return OK_Response;
        case 3: return REGISTER_CHILD;
        case 4: return ORGANIZING_LOGGED_OUT_Response;
        case 5: return FIND_ALL_SAMPLES_Response;
        case 6: return FIND_ORGANIZING_Response;
        case 7: return FIND_SAMPLE_Response;
        case 8: return LIST_CHILDREN_Response;
        case 9: return FIND_CHILD_Response;
        case 10: return SAVE_CHILD_Response;
        case 11: return REGISTER_CHILD_Response;
        case 12: return NEW_Response;
        case 13: return NUMBER_OF_CHILDREN_FOR_SAMPLE_Response;
        case 14: return ERROR_Response;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type_Response>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type_Response> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type_Response>() {
            public Type_Response findValueByNumber(int number) {
              return Type_Response.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CompetitionResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type_Response[] VALUES = values();

    public static Type_Response valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type_Response(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CompetitionResponse.Type_Response)
  }

  private int bitField0_;
  public static final int TYPE_RESPONSE_FIELD_NUMBER = 2;
  private int typeResponse_ = 0;
  /**
   * <code>.CompetitionResponse.Type_Response type_Response = 2;</code>
   * @return The enum numeric value on the wire for typeResponse.
   */
  @java.lang.Override public int getTypeResponseValue() {
    return typeResponse_;
  }
  /**
   * <code>.CompetitionResponse.Type_Response type_Response = 2;</code>
   * @return The typeResponse.
   */
  @java.lang.Override public CompetitionResponse.Type_Response getTypeResponse() {
    CompetitionResponse.Type_Response result = CompetitionResponse.Type_Response.forNumber(typeResponse_);
    return result == null ? CompetitionResponse.Type_Response.UNRECOGNIZED : result;
  }

  public static final int REGISTRATION_FIELD_NUMBER = 3;
  private RegistrationDTO registration_;
  /**
   * <code>.RegistrationDTO registration = 3;</code>
   * @return Whether the registration field is set.
   */
  @java.lang.Override
  public boolean hasRegistration() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.RegistrationDTO registration = 3;</code>
   * @return The registration.
   */
  @java.lang.Override
  public RegistrationDTO getRegistration() {
    return registration_ == null ? RegistrationDTO.getDefaultInstance() : registration_;
  }
  /**
   * <code>.RegistrationDTO registration = 3;</code>
   */
  @java.lang.Override
  public RegistrationDTOOrBuilder getRegistrationOrBuilder() {
    return registration_ == null ? RegistrationDTO.getDefaultInstance() : registration_;
  }

  public static final int ERROR_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private volatile java.lang.Object error_ = "";
  /**
   * <code>string error = 14;</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <code>string error = 14;</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORGANIZING_RESP_FIELD_NUMBER = 1;
  private OrganizingDTO organizingResp_;
  /**
   * <code>.OrganizingDTO organizing_resp = 1;</code>
   * @return Whether the organizingResp field is set.
   */
  @java.lang.Override
  public boolean hasOrganizingResp() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.OrganizingDTO organizing_resp = 1;</code>
   * @return The organizingResp.
   */
  @java.lang.Override
  public OrganizingDTO getOrganizingResp() {
    return organizingResp_ == null ? OrganizingDTO.getDefaultInstance() : organizingResp_;
  }
  /**
   * <code>.OrganizingDTO organizing_resp = 1;</code>
   */
  @java.lang.Override
  public OrganizingDTOOrBuilder getOrganizingRespOrBuilder() {
    return organizingResp_ == null ? OrganizingDTO.getDefaultInstance() : organizingResp_;
  }

  public static final int ORGANIZING_RESP2_FIELD_NUMBER = 4;
  private OrganizingDTO organizingResp2_;
  /**
   * <code>.OrganizingDTO organizing_resp2 = 4;</code>
   * @return Whether the organizingResp2 field is set.
   */
  @java.lang.Override
  public boolean hasOrganizingResp2() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.OrganizingDTO organizing_resp2 = 4;</code>
   * @return The organizingResp2.
   */
  @java.lang.Override
  public OrganizingDTO getOrganizingResp2() {
    return organizingResp2_ == null ? OrganizingDTO.getDefaultInstance() : organizingResp2_;
  }
  /**
   * <code>.OrganizingDTO organizing_resp2 = 4;</code>
   */
  @java.lang.Override
  public OrganizingDTOOrBuilder getOrganizingResp2OrBuilder() {
    return organizingResp2_ == null ? OrganizingDTO.getDefaultInstance() : organizingResp2_;
  }

  public static final int SAMPLES_RES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<SampleDTO> samplesRes_;
  /**
   * <code>repeated .SampleDTO samples_res = 5;</code>
   */
  @java.lang.Override
  public java.util.List<SampleDTO> getSamplesResList() {
    return samplesRes_;
  }
  /**
   * <code>repeated .SampleDTO samples_res = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends SampleDTOOrBuilder> 
      getSamplesResOrBuilderList() {
    return samplesRes_;
  }
  /**
   * <code>repeated .SampleDTO samples_res = 5;</code>
   */
  @java.lang.Override
  public int getSamplesResCount() {
    return samplesRes_.size();
  }
  /**
   * <code>repeated .SampleDTO samples_res = 5;</code>
   */
  @java.lang.Override
  public SampleDTO getSamplesRes(int index) {
    return samplesRes_.get(index);
  }
  /**
   * <code>repeated .SampleDTO samples_res = 5;</code>
   */
  @java.lang.Override
  public SampleDTOOrBuilder getSamplesResOrBuilder(
      int index) {
    return samplesRes_.get(index);
  }

  public static final int ORGANIZING_FIELD_NUMBER = 6;
  private OrganizingDTO organizing_;
  /**
   * <code>.OrganizingDTO organizing = 6;</code>
   * @return Whether the organizing field is set.
   */
  @java.lang.Override
  public boolean hasOrganizing() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.OrganizingDTO organizing = 6;</code>
   * @return The organizing.
   */
  @java.lang.Override
  public OrganizingDTO getOrganizing() {
    return organizing_ == null ? OrganizingDTO.getDefaultInstance() : organizing_;
  }
  /**
   * <code>.OrganizingDTO organizing = 6;</code>
   */
  @java.lang.Override
  public OrganizingDTOOrBuilder getOrganizingOrBuilder() {
    return organizing_ == null ? OrganizingDTO.getDefaultInstance() : organizing_;
  }

  public static final int SAMPLE_FIELD_NUMBER = 7;
  private SampleDTO sample_;
  /**
   * <code>.SampleDTO sample = 7;</code>
   * @return Whether the sample field is set.
   */
  @java.lang.Override
  public boolean hasSample() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.SampleDTO sample = 7;</code>
   * @return The sample.
   */
  @java.lang.Override
  public SampleDTO getSample() {
    return sample_ == null ? SampleDTO.getDefaultInstance() : sample_;
  }
  /**
   * <code>.SampleDTO sample = 7;</code>
   */
  @java.lang.Override
  public SampleDTOOrBuilder getSampleOrBuilder() {
    return sample_ == null ? SampleDTO.getDefaultInstance() : sample_;
  }

  public static final int CHILDREN_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<ChildDTO> children_;
  /**
   * <code>repeated .ChildDTO children = 8;</code>
   */
  @java.lang.Override
  public java.util.List<ChildDTO> getChildrenList() {
    return children_;
  }
  /**
   * <code>repeated .ChildDTO children = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ChildDTOOrBuilder> 
      getChildrenOrBuilderList() {
    return children_;
  }
  /**
   * <code>repeated .ChildDTO children = 8;</code>
   */
  @java.lang.Override
  public int getChildrenCount() {
    return children_.size();
  }
  /**
   * <code>repeated .ChildDTO children = 8;</code>
   */
  @java.lang.Override
  public ChildDTO getChildren(int index) {
    return children_.get(index);
  }
  /**
   * <code>repeated .ChildDTO children = 8;</code>
   */
  @java.lang.Override
  public ChildDTOOrBuilder getChildrenOrBuilder(
      int index) {
    return children_.get(index);
  }

  public static final int CHILD_FIELD_NUMBER = 9;
  private ChildDTO child_;
  /**
   * <code>.ChildDTO child = 9;</code>
   * @return Whether the child field is set.
   */
  @java.lang.Override
  public boolean hasChild() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>.ChildDTO child = 9;</code>
   * @return The child.
   */
  @java.lang.Override
  public ChildDTO getChild() {
    return child_ == null ? ChildDTO.getDefaultInstance() : child_;
  }
  /**
   * <code>.ChildDTO child = 9;</code>
   */
  @java.lang.Override
  public ChildDTOOrBuilder getChildOrBuilder() {
    return child_ == null ? ChildDTO.getDefaultInstance() : child_;
  }

  public static final int NEW_FIELD_NUMBER = 12;
  private New new_;
  /**
   * <code>.New new = 12;</code>
   * @return Whether the new field is set.
   */
  @java.lang.Override
  public boolean hasNew() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>.New new = 12;</code>
   * @return The new.
   */
  @java.lang.Override
  public New getNew() {
    return new_ == null ? New.getDefaultInstance() : new_;
  }
  /**
   * <code>.New new = 12;</code>
   */
  @java.lang.Override
  public NewOrBuilder getNewOrBuilder() {
    return new_ == null ? New.getDefaultInstance() : new_;
  }

  public static final int CHILD_SAVED_FIELD_NUMBER = 10;
  private ChildDTO childSaved_;
  /**
   * <code>.ChildDTO child_saved = 10;</code>
   * @return Whether the childSaved field is set.
   */
  @java.lang.Override
  public boolean hasChildSaved() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>.ChildDTO child_saved = 10;</code>
   * @return The childSaved.
   */
  @java.lang.Override
  public ChildDTO getChildSaved() {
    return childSaved_ == null ? ChildDTO.getDefaultInstance() : childSaved_;
  }
  /**
   * <code>.ChildDTO child_saved = 10;</code>
   */
  @java.lang.Override
  public ChildDTOOrBuilder getChildSavedOrBuilder() {
    return childSaved_ == null ? ChildDTO.getDefaultInstance() : childSaved_;
  }

  public static final int NUMBER_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object number_ = "";
  /**
   * <code>string number = 13;</code>
   * @return The number.
   */
  @java.lang.Override
  public java.lang.String getNumber() {
    java.lang.Object ref = number_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      number_ = s;
      return s;
    }
  }
  /**
   * <code>string number = 13;</code>
   * @return The bytes for number.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNumberBytes() {
    java.lang.Object ref = number_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      number_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(1, getOrganizingResp());
    }
    if (typeResponse_ != CompetitionResponse.Type_Response.Unknown_Response.getNumber()) {
      output.writeEnum(2, typeResponse_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getRegistration());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getOrganizingResp2());
    }
    for (int i = 0; i < samplesRes_.size(); i++) {
      output.writeMessage(5, samplesRes_.get(i));
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(6, getOrganizing());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(7, getSample());
    }
    for (int i = 0; i < children_.size(); i++) {
      output.writeMessage(8, children_.get(i));
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(9, getChild());
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeMessage(10, getChildSaved());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeMessage(12, getNew());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(number_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 13, number_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 14, error_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getOrganizingResp());
    }
    if (typeResponse_ != CompetitionResponse.Type_Response.Unknown_Response.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, typeResponse_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRegistration());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOrganizingResp2());
    }
    for (int i = 0; i < samplesRes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, samplesRes_.get(i));
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getOrganizing());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getSample());
    }
    for (int i = 0; i < children_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, children_.get(i));
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getChild());
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getChildSaved());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getNew());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(number_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(13, number_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(14, error_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CompetitionResponse)) {
      return super.equals(obj);
    }
    CompetitionResponse other = (CompetitionResponse) obj;

    if (typeResponse_ != other.typeResponse_) return false;
    if (hasRegistration() != other.hasRegistration()) return false;
    if (hasRegistration()) {
      if (!getRegistration()
          .equals(other.getRegistration())) return false;
    }
    if (!getError()
        .equals(other.getError())) return false;
    if (hasOrganizingResp() != other.hasOrganizingResp()) return false;
    if (hasOrganizingResp()) {
      if (!getOrganizingResp()
          .equals(other.getOrganizingResp())) return false;
    }
    if (hasOrganizingResp2() != other.hasOrganizingResp2()) return false;
    if (hasOrganizingResp2()) {
      if (!getOrganizingResp2()
          .equals(other.getOrganizingResp2())) return false;
    }
    if (!getSamplesResList()
        .equals(other.getSamplesResList())) return false;
    if (hasOrganizing() != other.hasOrganizing()) return false;
    if (hasOrganizing()) {
      if (!getOrganizing()
          .equals(other.getOrganizing())) return false;
    }
    if (hasSample() != other.hasSample()) return false;
    if (hasSample()) {
      if (!getSample()
          .equals(other.getSample())) return false;
    }
    if (!getChildrenList()
        .equals(other.getChildrenList())) return false;
    if (hasChild() != other.hasChild()) return false;
    if (hasChild()) {
      if (!getChild()
          .equals(other.getChild())) return false;
    }
    if (hasNew() != other.hasNew()) return false;
    if (hasNew()) {
      if (!getNew()
          .equals(other.getNew())) return false;
    }
    if (hasChildSaved() != other.hasChildSaved()) return false;
    if (hasChildSaved()) {
      if (!getChildSaved()
          .equals(other.getChildSaved())) return false;
    }
    if (!getNumber()
        .equals(other.getNumber())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_RESPONSE_FIELD_NUMBER;
    hash = (53 * hash) + typeResponse_;
    if (hasRegistration()) {
      hash = (37 * hash) + REGISTRATION_FIELD_NUMBER;
      hash = (53 * hash) + getRegistration().hashCode();
    }
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    if (hasOrganizingResp()) {
      hash = (37 * hash) + ORGANIZING_RESP_FIELD_NUMBER;
      hash = (53 * hash) + getOrganizingResp().hashCode();
    }
    if (hasOrganizingResp2()) {
      hash = (37 * hash) + ORGANIZING_RESP2_FIELD_NUMBER;
      hash = (53 * hash) + getOrganizingResp2().hashCode();
    }
    if (getSamplesResCount() > 0) {
      hash = (37 * hash) + SAMPLES_RES_FIELD_NUMBER;
      hash = (53 * hash) + getSamplesResList().hashCode();
    }
    if (hasOrganizing()) {
      hash = (37 * hash) + ORGANIZING_FIELD_NUMBER;
      hash = (53 * hash) + getOrganizing().hashCode();
    }
    if (hasSample()) {
      hash = (37 * hash) + SAMPLE_FIELD_NUMBER;
      hash = (53 * hash) + getSample().hashCode();
    }
    if (getChildrenCount() > 0) {
      hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
      hash = (53 * hash) + getChildrenList().hashCode();
    }
    if (hasChild()) {
      hash = (37 * hash) + CHILD_FIELD_NUMBER;
      hash = (53 * hash) + getChild().hashCode();
    }
    if (hasNew()) {
      hash = (37 * hash) + NEW_FIELD_NUMBER;
      hash = (53 * hash) + getNew().hashCode();
    }
    if (hasChildSaved()) {
      hash = (37 * hash) + CHILD_SAVED_FIELD_NUMBER;
      hash = (53 * hash) + getChildSaved().hashCode();
    }
    hash = (37 * hash) + NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getNumber().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CompetitionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CompetitionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CompetitionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CompetitionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CompetitionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CompetitionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CompetitionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static CompetitionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static CompetitionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static CompetitionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CompetitionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static CompetitionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CompetitionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CompetitionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CompetitionResponse)
      CompetitionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CompetitionProtobuf.internal_static_CompetitionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CompetitionProtobuf.internal_static_CompetitionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CompetitionResponse.class, CompetitionResponse.Builder.class);
    }

    // Construct using CompetitionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getRegistrationFieldBuilder();
        getOrganizingRespFieldBuilder();
        getOrganizingResp2FieldBuilder();
        getSamplesResFieldBuilder();
        getOrganizingFieldBuilder();
        getSampleFieldBuilder();
        getChildrenFieldBuilder();
        getChildFieldBuilder();
        getNewFieldBuilder();
        getChildSavedFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      typeResponse_ = 0;
      registration_ = null;
      if (registrationBuilder_ != null) {
        registrationBuilder_.dispose();
        registrationBuilder_ = null;
      }
      error_ = "";
      organizingResp_ = null;
      if (organizingRespBuilder_ != null) {
        organizingRespBuilder_.dispose();
        organizingRespBuilder_ = null;
      }
      organizingResp2_ = null;
      if (organizingResp2Builder_ != null) {
        organizingResp2Builder_.dispose();
        organizingResp2Builder_ = null;
      }
      if (samplesResBuilder_ == null) {
        samplesRes_ = java.util.Collections.emptyList();
      } else {
        samplesRes_ = null;
        samplesResBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      organizing_ = null;
      if (organizingBuilder_ != null) {
        organizingBuilder_.dispose();
        organizingBuilder_ = null;
      }
      sample_ = null;
      if (sampleBuilder_ != null) {
        sampleBuilder_.dispose();
        sampleBuilder_ = null;
      }
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
      } else {
        children_ = null;
        childrenBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      child_ = null;
      if (childBuilder_ != null) {
        childBuilder_.dispose();
        childBuilder_ = null;
      }
      new_ = null;
      if (newBuilder_ != null) {
        newBuilder_.dispose();
        newBuilder_ = null;
      }
      childSaved_ = null;
      if (childSavedBuilder_ != null) {
        childSavedBuilder_.dispose();
        childSavedBuilder_ = null;
      }
      number_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CompetitionProtobuf.internal_static_CompetitionResponse_descriptor;
    }

    @java.lang.Override
    public CompetitionResponse getDefaultInstanceForType() {
      return CompetitionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public CompetitionResponse build() {
      CompetitionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CompetitionResponse buildPartial() {
      CompetitionResponse result = new CompetitionResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(CompetitionResponse result) {
      if (samplesResBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          samplesRes_ = java.util.Collections.unmodifiableList(samplesRes_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.samplesRes_ = samplesRes_;
      } else {
        result.samplesRes_ = samplesResBuilder_.build();
      }
      if (childrenBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0)) {
          children_ = java.util.Collections.unmodifiableList(children_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.children_ = children_;
      } else {
        result.children_ = childrenBuilder_.build();
      }
    }

    private void buildPartial0(CompetitionResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.typeResponse_ = typeResponse_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.registration_ = registrationBuilder_ == null
            ? registration_
            : registrationBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.error_ = error_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.organizingResp_ = organizingRespBuilder_ == null
            ? organizingResp_
            : organizingRespBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.organizingResp2_ = organizingResp2Builder_ == null
            ? organizingResp2_
            : organizingResp2Builder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.organizing_ = organizingBuilder_ == null
            ? organizing_
            : organizingBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.sample_ = sampleBuilder_ == null
            ? sample_
            : sampleBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.child_ = childBuilder_ == null
            ? child_
            : childBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.new_ = newBuilder_ == null
            ? new_
            : newBuilder_.build();
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.childSaved_ = childSavedBuilder_ == null
            ? childSaved_
            : childSavedBuilder_.build();
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.number_ = number_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CompetitionResponse) {
        return mergeFrom((CompetitionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CompetitionResponse other) {
      if (other == CompetitionResponse.getDefaultInstance()) return this;
      if (other.typeResponse_ != 0) {
        setTypeResponseValue(other.getTypeResponseValue());
      }
      if (other.hasRegistration()) {
        mergeRegistration(other.getRegistration());
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasOrganizingResp()) {
        mergeOrganizingResp(other.getOrganizingResp());
      }
      if (other.hasOrganizingResp2()) {
        mergeOrganizingResp2(other.getOrganizingResp2());
      }
      if (samplesResBuilder_ == null) {
        if (!other.samplesRes_.isEmpty()) {
          if (samplesRes_.isEmpty()) {
            samplesRes_ = other.samplesRes_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureSamplesResIsMutable();
            samplesRes_.addAll(other.samplesRes_);
          }
          onChanged();
        }
      } else {
        if (!other.samplesRes_.isEmpty()) {
          if (samplesResBuilder_.isEmpty()) {
            samplesResBuilder_.dispose();
            samplesResBuilder_ = null;
            samplesRes_ = other.samplesRes_;
            bitField0_ = (bitField0_ & ~0x00000020);
            samplesResBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getSamplesResFieldBuilder() : null;
          } else {
            samplesResBuilder_.addAllMessages(other.samplesRes_);
          }
        }
      }
      if (other.hasOrganizing()) {
        mergeOrganizing(other.getOrganizing());
      }
      if (other.hasSample()) {
        mergeSample(other.getSample());
      }
      if (childrenBuilder_ == null) {
        if (!other.children_.isEmpty()) {
          if (children_.isEmpty()) {
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureChildrenIsMutable();
            children_.addAll(other.children_);
          }
          onChanged();
        }
      } else {
        if (!other.children_.isEmpty()) {
          if (childrenBuilder_.isEmpty()) {
            childrenBuilder_.dispose();
            childrenBuilder_ = null;
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000100);
            childrenBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getChildrenFieldBuilder() : null;
          } else {
            childrenBuilder_.addAllMessages(other.children_);
          }
        }
      }
      if (other.hasChild()) {
        mergeChild(other.getChild());
      }
      if (other.hasNew()) {
        mergeNew(other.getNew());
      }
      if (other.hasChildSaved()) {
        mergeChildSaved(other.getChildSaved());
      }
      if (!other.getNumber().isEmpty()) {
        number_ = other.number_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getOrganizingRespFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 10
            case 16: {
              typeResponse_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getRegistrationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getOrganizingResp2FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 34
            case 42: {
              SampleDTO m =
                  input.readMessage(
                      SampleDTO.parser(),
                      extensionRegistry);
              if (samplesResBuilder_ == null) {
                ensureSamplesResIsMutable();
                samplesRes_.add(m);
              } else {
                samplesResBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getOrganizingFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getSampleFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 58
            case 66: {
              ChildDTO m =
                  input.readMessage(
                      ChildDTO.parser(),
                      extensionRegistry);
              if (childrenBuilder_ == null) {
                ensureChildrenIsMutable();
                children_.add(m);
              } else {
                childrenBuilder_.addMessage(m);
              }
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getChildFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000200;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  getChildSavedFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000800;
              break;
            } // case 82
            case 98: {
              input.readMessage(
                  getNewFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000400;
              break;
            } // case 98
            case 106: {
              number_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 114: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 114
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int typeResponse_ = 0;
    /**
     * <code>.CompetitionResponse.Type_Response type_Response = 2;</code>
     * @return The enum numeric value on the wire for typeResponse.
     */
    @java.lang.Override public int getTypeResponseValue() {
      return typeResponse_;
    }
    /**
     * <code>.CompetitionResponse.Type_Response type_Response = 2;</code>
     * @param value The enum numeric value on the wire for typeResponse to set.
     * @return This builder for chaining.
     */
    public Builder setTypeResponseValue(int value) {
      typeResponse_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.CompetitionResponse.Type_Response type_Response = 2;</code>
     * @return The typeResponse.
     */
    @java.lang.Override
    public CompetitionResponse.Type_Response getTypeResponse() {
      CompetitionResponse.Type_Response result = CompetitionResponse.Type_Response.forNumber(typeResponse_);
      return result == null ? CompetitionResponse.Type_Response.UNRECOGNIZED : result;
    }
    /**
     * <code>.CompetitionResponse.Type_Response type_Response = 2;</code>
     * @param value The typeResponse to set.
     * @return This builder for chaining.
     */
    public Builder setTypeResponse(CompetitionResponse.Type_Response value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      typeResponse_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.CompetitionResponse.Type_Response type_Response = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      typeResponse_ = 0;
      onChanged();
      return this;
    }

    private RegistrationDTO registration_;
    private com.google.protobuf.SingleFieldBuilder<
        RegistrationDTO, RegistrationDTO.Builder, RegistrationDTOOrBuilder> registrationBuilder_;
    /**
     * <code>.RegistrationDTO registration = 3;</code>
     * @return Whether the registration field is set.
     */
    public boolean hasRegistration() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.RegistrationDTO registration = 3;</code>
     * @return The registration.
     */
    public RegistrationDTO getRegistration() {
      if (registrationBuilder_ == null) {
        return registration_ == null ? RegistrationDTO.getDefaultInstance() : registration_;
      } else {
        return registrationBuilder_.getMessage();
      }
    }
    /**
     * <code>.RegistrationDTO registration = 3;</code>
     */
    public Builder setRegistration(RegistrationDTO value) {
      if (registrationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        registration_ = value;
      } else {
        registrationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.RegistrationDTO registration = 3;</code>
     */
    public Builder setRegistration(
        RegistrationDTO.Builder builderForValue) {
      if (registrationBuilder_ == null) {
        registration_ = builderForValue.build();
      } else {
        registrationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.RegistrationDTO registration = 3;</code>
     */
    public Builder mergeRegistration(RegistrationDTO value) {
      if (registrationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          registration_ != null &&
          registration_ != RegistrationDTO.getDefaultInstance()) {
          getRegistrationBuilder().mergeFrom(value);
        } else {
          registration_ = value;
        }
      } else {
        registrationBuilder_.mergeFrom(value);
      }
      if (registration_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.RegistrationDTO registration = 3;</code>
     */
    public Builder clearRegistration() {
      bitField0_ = (bitField0_ & ~0x00000002);
      registration_ = null;
      if (registrationBuilder_ != null) {
        registrationBuilder_.dispose();
        registrationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.RegistrationDTO registration = 3;</code>
     */
    public RegistrationDTO.Builder getRegistrationBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getRegistrationFieldBuilder().getBuilder();
    }
    /**
     * <code>.RegistrationDTO registration = 3;</code>
     */
    public RegistrationDTOOrBuilder getRegistrationOrBuilder() {
      if (registrationBuilder_ != null) {
        return registrationBuilder_.getMessageOrBuilder();
      } else {
        return registration_ == null ?
            RegistrationDTO.getDefaultInstance() : registration_;
      }
    }
    /**
     * <code>.RegistrationDTO registration = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        RegistrationDTO, RegistrationDTO.Builder, RegistrationDTOOrBuilder> 
        getRegistrationFieldBuilder() {
      if (registrationBuilder_ == null) {
        registrationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            RegistrationDTO, RegistrationDTO.Builder, RegistrationDTOOrBuilder>(
                getRegistration(),
                getParentForChildren(),
                isClean());
        registration_ = null;
      }
      return registrationBuilder_;
    }

    private java.lang.Object error_ = "";
    /**
     * <code>string error = 14;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error = 14;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error = 14;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      error_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string error = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string error = 14;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private OrganizingDTO organizingResp_;
    private com.google.protobuf.SingleFieldBuilder<
        OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder> organizingRespBuilder_;
    /**
     * <code>.OrganizingDTO organizing_resp = 1;</code>
     * @return Whether the organizingResp field is set.
     */
    public boolean hasOrganizingResp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.OrganizingDTO organizing_resp = 1;</code>
     * @return The organizingResp.
     */
    public OrganizingDTO getOrganizingResp() {
      if (organizingRespBuilder_ == null) {
        return organizingResp_ == null ? OrganizingDTO.getDefaultInstance() : organizingResp_;
      } else {
        return organizingRespBuilder_.getMessage();
      }
    }
    /**
     * <code>.OrganizingDTO organizing_resp = 1;</code>
     */
    public Builder setOrganizingResp(OrganizingDTO value) {
      if (organizingRespBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        organizingResp_ = value;
      } else {
        organizingRespBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_resp = 1;</code>
     */
    public Builder setOrganizingResp(
        OrganizingDTO.Builder builderForValue) {
      if (organizingRespBuilder_ == null) {
        organizingResp_ = builderForValue.build();
      } else {
        organizingRespBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_resp = 1;</code>
     */
    public Builder mergeOrganizingResp(OrganizingDTO value) {
      if (organizingRespBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          organizingResp_ != null &&
          organizingResp_ != OrganizingDTO.getDefaultInstance()) {
          getOrganizingRespBuilder().mergeFrom(value);
        } else {
          organizingResp_ = value;
        }
      } else {
        organizingRespBuilder_.mergeFrom(value);
      }
      if (organizingResp_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_resp = 1;</code>
     */
    public Builder clearOrganizingResp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      organizingResp_ = null;
      if (organizingRespBuilder_ != null) {
        organizingRespBuilder_.dispose();
        organizingRespBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_resp = 1;</code>
     */
    public OrganizingDTO.Builder getOrganizingRespBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getOrganizingRespFieldBuilder().getBuilder();
    }
    /**
     * <code>.OrganizingDTO organizing_resp = 1;</code>
     */
    public OrganizingDTOOrBuilder getOrganizingRespOrBuilder() {
      if (organizingRespBuilder_ != null) {
        return organizingRespBuilder_.getMessageOrBuilder();
      } else {
        return organizingResp_ == null ?
            OrganizingDTO.getDefaultInstance() : organizingResp_;
      }
    }
    /**
     * <code>.OrganizingDTO organizing_resp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder> 
        getOrganizingRespFieldBuilder() {
      if (organizingRespBuilder_ == null) {
        organizingRespBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder>(
                getOrganizingResp(),
                getParentForChildren(),
                isClean());
        organizingResp_ = null;
      }
      return organizingRespBuilder_;
    }

    private OrganizingDTO organizingResp2_;
    private com.google.protobuf.SingleFieldBuilder<
        OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder> organizingResp2Builder_;
    /**
     * <code>.OrganizingDTO organizing_resp2 = 4;</code>
     * @return Whether the organizingResp2 field is set.
     */
    public boolean hasOrganizingResp2() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.OrganizingDTO organizing_resp2 = 4;</code>
     * @return The organizingResp2.
     */
    public OrganizingDTO getOrganizingResp2() {
      if (organizingResp2Builder_ == null) {
        return organizingResp2_ == null ? OrganizingDTO.getDefaultInstance() : organizingResp2_;
      } else {
        return organizingResp2Builder_.getMessage();
      }
    }
    /**
     * <code>.OrganizingDTO organizing_resp2 = 4;</code>
     */
    public Builder setOrganizingResp2(OrganizingDTO value) {
      if (organizingResp2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        organizingResp2_ = value;
      } else {
        organizingResp2Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_resp2 = 4;</code>
     */
    public Builder setOrganizingResp2(
        OrganizingDTO.Builder builderForValue) {
      if (organizingResp2Builder_ == null) {
        organizingResp2_ = builderForValue.build();
      } else {
        organizingResp2Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_resp2 = 4;</code>
     */
    public Builder mergeOrganizingResp2(OrganizingDTO value) {
      if (organizingResp2Builder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          organizingResp2_ != null &&
          organizingResp2_ != OrganizingDTO.getDefaultInstance()) {
          getOrganizingResp2Builder().mergeFrom(value);
        } else {
          organizingResp2_ = value;
        }
      } else {
        organizingResp2Builder_.mergeFrom(value);
      }
      if (organizingResp2_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_resp2 = 4;</code>
     */
    public Builder clearOrganizingResp2() {
      bitField0_ = (bitField0_ & ~0x00000010);
      organizingResp2_ = null;
      if (organizingResp2Builder_ != null) {
        organizingResp2Builder_.dispose();
        organizingResp2Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing_resp2 = 4;</code>
     */
    public OrganizingDTO.Builder getOrganizingResp2Builder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getOrganizingResp2FieldBuilder().getBuilder();
    }
    /**
     * <code>.OrganizingDTO organizing_resp2 = 4;</code>
     */
    public OrganizingDTOOrBuilder getOrganizingResp2OrBuilder() {
      if (organizingResp2Builder_ != null) {
        return organizingResp2Builder_.getMessageOrBuilder();
      } else {
        return organizingResp2_ == null ?
            OrganizingDTO.getDefaultInstance() : organizingResp2_;
      }
    }
    /**
     * <code>.OrganizingDTO organizing_resp2 = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder> 
        getOrganizingResp2FieldBuilder() {
      if (organizingResp2Builder_ == null) {
        organizingResp2Builder_ = new com.google.protobuf.SingleFieldBuilder<
            OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder>(
                getOrganizingResp2(),
                getParentForChildren(),
                isClean());
        organizingResp2_ = null;
      }
      return organizingResp2Builder_;
    }

    private java.util.List<SampleDTO> samplesRes_ =
      java.util.Collections.emptyList();
    private void ensureSamplesResIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        samplesRes_ = new java.util.ArrayList<SampleDTO>(samplesRes_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder> samplesResBuilder_;

    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public java.util.List<SampleDTO> getSamplesResList() {
      if (samplesResBuilder_ == null) {
        return java.util.Collections.unmodifiableList(samplesRes_);
      } else {
        return samplesResBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public int getSamplesResCount() {
      if (samplesResBuilder_ == null) {
        return samplesRes_.size();
      } else {
        return samplesResBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public SampleDTO getSamplesRes(int index) {
      if (samplesResBuilder_ == null) {
        return samplesRes_.get(index);
      } else {
        return samplesResBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public Builder setSamplesRes(
        int index, SampleDTO value) {
      if (samplesResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSamplesResIsMutable();
        samplesRes_.set(index, value);
        onChanged();
      } else {
        samplesResBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public Builder setSamplesRes(
        int index, SampleDTO.Builder builderForValue) {
      if (samplesResBuilder_ == null) {
        ensureSamplesResIsMutable();
        samplesRes_.set(index, builderForValue.build());
        onChanged();
      } else {
        samplesResBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public Builder addSamplesRes(SampleDTO value) {
      if (samplesResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSamplesResIsMutable();
        samplesRes_.add(value);
        onChanged();
      } else {
        samplesResBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public Builder addSamplesRes(
        int index, SampleDTO value) {
      if (samplesResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSamplesResIsMutable();
        samplesRes_.add(index, value);
        onChanged();
      } else {
        samplesResBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public Builder addSamplesRes(
        SampleDTO.Builder builderForValue) {
      if (samplesResBuilder_ == null) {
        ensureSamplesResIsMutable();
        samplesRes_.add(builderForValue.build());
        onChanged();
      } else {
        samplesResBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public Builder addSamplesRes(
        int index, SampleDTO.Builder builderForValue) {
      if (samplesResBuilder_ == null) {
        ensureSamplesResIsMutable();
        samplesRes_.add(index, builderForValue.build());
        onChanged();
      } else {
        samplesResBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public Builder addAllSamplesRes(
        java.lang.Iterable<? extends SampleDTO> values) {
      if (samplesResBuilder_ == null) {
        ensureSamplesResIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, samplesRes_);
        onChanged();
      } else {
        samplesResBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public Builder clearSamplesRes() {
      if (samplesResBuilder_ == null) {
        samplesRes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        samplesResBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public Builder removeSamplesRes(int index) {
      if (samplesResBuilder_ == null) {
        ensureSamplesResIsMutable();
        samplesRes_.remove(index);
        onChanged();
      } else {
        samplesResBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public SampleDTO.Builder getSamplesResBuilder(
        int index) {
      return getSamplesResFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public SampleDTOOrBuilder getSamplesResOrBuilder(
        int index) {
      if (samplesResBuilder_ == null) {
        return samplesRes_.get(index);  } else {
        return samplesResBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public java.util.List<? extends SampleDTOOrBuilder> 
         getSamplesResOrBuilderList() {
      if (samplesResBuilder_ != null) {
        return samplesResBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(samplesRes_);
      }
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public SampleDTO.Builder addSamplesResBuilder() {
      return getSamplesResFieldBuilder().addBuilder(
          SampleDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public SampleDTO.Builder addSamplesResBuilder(
        int index) {
      return getSamplesResFieldBuilder().addBuilder(
          index, SampleDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .SampleDTO samples_res = 5;</code>
     */
    public java.util.List<SampleDTO.Builder> 
         getSamplesResBuilderList() {
      return getSamplesResFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder> 
        getSamplesResFieldBuilder() {
      if (samplesResBuilder_ == null) {
        samplesResBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder>(
                samplesRes_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        samplesRes_ = null;
      }
      return samplesResBuilder_;
    }

    private OrganizingDTO organizing_;
    private com.google.protobuf.SingleFieldBuilder<
        OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder> organizingBuilder_;
    /**
     * <code>.OrganizingDTO organizing = 6;</code>
     * @return Whether the organizing field is set.
     */
    public boolean hasOrganizing() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.OrganizingDTO organizing = 6;</code>
     * @return The organizing.
     */
    public OrganizingDTO getOrganizing() {
      if (organizingBuilder_ == null) {
        return organizing_ == null ? OrganizingDTO.getDefaultInstance() : organizing_;
      } else {
        return organizingBuilder_.getMessage();
      }
    }
    /**
     * <code>.OrganizingDTO organizing = 6;</code>
     */
    public Builder setOrganizing(OrganizingDTO value) {
      if (organizingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        organizing_ = value;
      } else {
        organizingBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing = 6;</code>
     */
    public Builder setOrganizing(
        OrganizingDTO.Builder builderForValue) {
      if (organizingBuilder_ == null) {
        organizing_ = builderForValue.build();
      } else {
        organizingBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing = 6;</code>
     */
    public Builder mergeOrganizing(OrganizingDTO value) {
      if (organizingBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          organizing_ != null &&
          organizing_ != OrganizingDTO.getDefaultInstance()) {
          getOrganizingBuilder().mergeFrom(value);
        } else {
          organizing_ = value;
        }
      } else {
        organizingBuilder_.mergeFrom(value);
      }
      if (organizing_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing = 6;</code>
     */
    public Builder clearOrganizing() {
      bitField0_ = (bitField0_ & ~0x00000040);
      organizing_ = null;
      if (organizingBuilder_ != null) {
        organizingBuilder_.dispose();
        organizingBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.OrganizingDTO organizing = 6;</code>
     */
    public OrganizingDTO.Builder getOrganizingBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getOrganizingFieldBuilder().getBuilder();
    }
    /**
     * <code>.OrganizingDTO organizing = 6;</code>
     */
    public OrganizingDTOOrBuilder getOrganizingOrBuilder() {
      if (organizingBuilder_ != null) {
        return organizingBuilder_.getMessageOrBuilder();
      } else {
        return organizing_ == null ?
            OrganizingDTO.getDefaultInstance() : organizing_;
      }
    }
    /**
     * <code>.OrganizingDTO organizing = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder> 
        getOrganizingFieldBuilder() {
      if (organizingBuilder_ == null) {
        organizingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            OrganizingDTO, OrganizingDTO.Builder, OrganizingDTOOrBuilder>(
                getOrganizing(),
                getParentForChildren(),
                isClean());
        organizing_ = null;
      }
      return organizingBuilder_;
    }

    private SampleDTO sample_;
    private com.google.protobuf.SingleFieldBuilder<
        SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder> sampleBuilder_;
    /**
     * <code>.SampleDTO sample = 7;</code>
     * @return Whether the sample field is set.
     */
    public boolean hasSample() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.SampleDTO sample = 7;</code>
     * @return The sample.
     */
    public SampleDTO getSample() {
      if (sampleBuilder_ == null) {
        return sample_ == null ? SampleDTO.getDefaultInstance() : sample_;
      } else {
        return sampleBuilder_.getMessage();
      }
    }
    /**
     * <code>.SampleDTO sample = 7;</code>
     */
    public Builder setSample(SampleDTO value) {
      if (sampleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sample_ = value;
      } else {
        sampleBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.SampleDTO sample = 7;</code>
     */
    public Builder setSample(
        SampleDTO.Builder builderForValue) {
      if (sampleBuilder_ == null) {
        sample_ = builderForValue.build();
      } else {
        sampleBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.SampleDTO sample = 7;</code>
     */
    public Builder mergeSample(SampleDTO value) {
      if (sampleBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          sample_ != null &&
          sample_ != SampleDTO.getDefaultInstance()) {
          getSampleBuilder().mergeFrom(value);
        } else {
          sample_ = value;
        }
      } else {
        sampleBuilder_.mergeFrom(value);
      }
      if (sample_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.SampleDTO sample = 7;</code>
     */
    public Builder clearSample() {
      bitField0_ = (bitField0_ & ~0x00000080);
      sample_ = null;
      if (sampleBuilder_ != null) {
        sampleBuilder_.dispose();
        sampleBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.SampleDTO sample = 7;</code>
     */
    public SampleDTO.Builder getSampleBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getSampleFieldBuilder().getBuilder();
    }
    /**
     * <code>.SampleDTO sample = 7;</code>
     */
    public SampleDTOOrBuilder getSampleOrBuilder() {
      if (sampleBuilder_ != null) {
        return sampleBuilder_.getMessageOrBuilder();
      } else {
        return sample_ == null ?
            SampleDTO.getDefaultInstance() : sample_;
      }
    }
    /**
     * <code>.SampleDTO sample = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder> 
        getSampleFieldBuilder() {
      if (sampleBuilder_ == null) {
        sampleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            SampleDTO, SampleDTO.Builder, SampleDTOOrBuilder>(
                getSample(),
                getParentForChildren(),
                isClean());
        sample_ = null;
      }
      return sampleBuilder_;
    }

    private java.util.List<ChildDTO> children_ =
      java.util.Collections.emptyList();
    private void ensureChildrenIsMutable() {
      if (!((bitField0_ & 0x00000100) != 0)) {
        children_ = new java.util.ArrayList<ChildDTO>(children_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder> childrenBuilder_;

    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public java.util.List<ChildDTO> getChildrenList() {
      if (childrenBuilder_ == null) {
        return java.util.Collections.unmodifiableList(children_);
      } else {
        return childrenBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public int getChildrenCount() {
      if (childrenBuilder_ == null) {
        return children_.size();
      } else {
        return childrenBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public ChildDTO getChildren(int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);
      } else {
        return childrenBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public Builder setChildren(
        int index, ChildDTO value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.set(index, value);
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public Builder setChildren(
        int index, ChildDTO.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.set(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public Builder addChildren(ChildDTO value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public Builder addChildren(
        int index, ChildDTO value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(index, value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public Builder addChildren(
        ChildDTO.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public Builder addChildren(
        int index, ChildDTO.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public Builder addAllChildren(
        java.lang.Iterable<? extends ChildDTO> values) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, children_);
        onChanged();
      } else {
        childrenBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public Builder clearChildren() {
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        childrenBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public Builder removeChildren(int index) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.remove(index);
        onChanged();
      } else {
        childrenBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public ChildDTO.Builder getChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public ChildDTOOrBuilder getChildrenOrBuilder(
        int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);  } else {
        return childrenBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public java.util.List<? extends ChildDTOOrBuilder> 
         getChildrenOrBuilderList() {
      if (childrenBuilder_ != null) {
        return childrenBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(children_);
      }
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public ChildDTO.Builder addChildrenBuilder() {
      return getChildrenFieldBuilder().addBuilder(
          ChildDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public ChildDTO.Builder addChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().addBuilder(
          index, ChildDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .ChildDTO children = 8;</code>
     */
    public java.util.List<ChildDTO.Builder> 
         getChildrenBuilderList() {
      return getChildrenFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder> 
        getChildrenFieldBuilder() {
      if (childrenBuilder_ == null) {
        childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder>(
                children_,
                ((bitField0_ & 0x00000100) != 0),
                getParentForChildren(),
                isClean());
        children_ = null;
      }
      return childrenBuilder_;
    }

    private ChildDTO child_;
    private com.google.protobuf.SingleFieldBuilder<
        ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder> childBuilder_;
    /**
     * <code>.ChildDTO child = 9;</code>
     * @return Whether the child field is set.
     */
    public boolean hasChild() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>.ChildDTO child = 9;</code>
     * @return The child.
     */
    public ChildDTO getChild() {
      if (childBuilder_ == null) {
        return child_ == null ? ChildDTO.getDefaultInstance() : child_;
      } else {
        return childBuilder_.getMessage();
      }
    }
    /**
     * <code>.ChildDTO child = 9;</code>
     */
    public Builder setChild(ChildDTO value) {
      if (childBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        child_ = value;
      } else {
        childBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.ChildDTO child = 9;</code>
     */
    public Builder setChild(
        ChildDTO.Builder builderForValue) {
      if (childBuilder_ == null) {
        child_ = builderForValue.build();
      } else {
        childBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.ChildDTO child = 9;</code>
     */
    public Builder mergeChild(ChildDTO value) {
      if (childBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
          child_ != null &&
          child_ != ChildDTO.getDefaultInstance()) {
          getChildBuilder().mergeFrom(value);
        } else {
          child_ = value;
        }
      } else {
        childBuilder_.mergeFrom(value);
      }
      if (child_ != null) {
        bitField0_ |= 0x00000200;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ChildDTO child = 9;</code>
     */
    public Builder clearChild() {
      bitField0_ = (bitField0_ & ~0x00000200);
      child_ = null;
      if (childBuilder_ != null) {
        childBuilder_.dispose();
        childBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ChildDTO child = 9;</code>
     */
    public ChildDTO.Builder getChildBuilder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return getChildFieldBuilder().getBuilder();
    }
    /**
     * <code>.ChildDTO child = 9;</code>
     */
    public ChildDTOOrBuilder getChildOrBuilder() {
      if (childBuilder_ != null) {
        return childBuilder_.getMessageOrBuilder();
      } else {
        return child_ == null ?
            ChildDTO.getDefaultInstance() : child_;
      }
    }
    /**
     * <code>.ChildDTO child = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder> 
        getChildFieldBuilder() {
      if (childBuilder_ == null) {
        childBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder>(
                getChild(),
                getParentForChildren(),
                isClean());
        child_ = null;
      }
      return childBuilder_;
    }

    private New new_;
    private com.google.protobuf.SingleFieldBuilder<
        New, New.Builder, NewOrBuilder> newBuilder_;
    /**
     * <code>.New new = 12;</code>
     * @return Whether the new field is set.
     */
    public boolean hasNew() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>.New new = 12;</code>
     * @return The new.
     */
    public New getNew() {
      if (newBuilder_ == null) {
        return new_ == null ? New.getDefaultInstance() : new_;
      } else {
        return newBuilder_.getMessage();
      }
    }
    /**
     * <code>.New new = 12;</code>
     */
    public Builder setNew(New value) {
      if (newBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        new_ = value;
      } else {
        newBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.New new = 12;</code>
     */
    public Builder setNew(
        New.Builder builderForValue) {
      if (newBuilder_ == null) {
        new_ = builderForValue.build();
      } else {
        newBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.New new = 12;</code>
     */
    public Builder mergeNew(New value) {
      if (newBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
          new_ != null &&
          new_ != New.getDefaultInstance()) {
          getNewBuilder().mergeFrom(value);
        } else {
          new_ = value;
        }
      } else {
        newBuilder_.mergeFrom(value);
      }
      if (new_ != null) {
        bitField0_ |= 0x00000400;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.New new = 12;</code>
     */
    public Builder clearNew() {
      bitField0_ = (bitField0_ & ~0x00000400);
      new_ = null;
      if (newBuilder_ != null) {
        newBuilder_.dispose();
        newBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.New new = 12;</code>
     */
    public New.Builder getNewBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getNewFieldBuilder().getBuilder();
    }
    /**
     * <code>.New new = 12;</code>
     */
    public NewOrBuilder getNewOrBuilder() {
      if (newBuilder_ != null) {
        return newBuilder_.getMessageOrBuilder();
      } else {
        return new_ == null ?
            New.getDefaultInstance() : new_;
      }
    }
    /**
     * <code>.New new = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        New, New.Builder, NewOrBuilder> 
        getNewFieldBuilder() {
      if (newBuilder_ == null) {
        newBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            New, New.Builder, NewOrBuilder>(
                getNew(),
                getParentForChildren(),
                isClean());
        new_ = null;
      }
      return newBuilder_;
    }

    private ChildDTO childSaved_;
    private com.google.protobuf.SingleFieldBuilder<
        ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder> childSavedBuilder_;
    /**
     * <code>.ChildDTO child_saved = 10;</code>
     * @return Whether the childSaved field is set.
     */
    public boolean hasChildSaved() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>.ChildDTO child_saved = 10;</code>
     * @return The childSaved.
     */
    public ChildDTO getChildSaved() {
      if (childSavedBuilder_ == null) {
        return childSaved_ == null ? ChildDTO.getDefaultInstance() : childSaved_;
      } else {
        return childSavedBuilder_.getMessage();
      }
    }
    /**
     * <code>.ChildDTO child_saved = 10;</code>
     */
    public Builder setChildSaved(ChildDTO value) {
      if (childSavedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        childSaved_ = value;
      } else {
        childSavedBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.ChildDTO child_saved = 10;</code>
     */
    public Builder setChildSaved(
        ChildDTO.Builder builderForValue) {
      if (childSavedBuilder_ == null) {
        childSaved_ = builderForValue.build();
      } else {
        childSavedBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.ChildDTO child_saved = 10;</code>
     */
    public Builder mergeChildSaved(ChildDTO value) {
      if (childSavedBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0) &&
          childSaved_ != null &&
          childSaved_ != ChildDTO.getDefaultInstance()) {
          getChildSavedBuilder().mergeFrom(value);
        } else {
          childSaved_ = value;
        }
      } else {
        childSavedBuilder_.mergeFrom(value);
      }
      if (childSaved_ != null) {
        bitField0_ |= 0x00000800;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ChildDTO child_saved = 10;</code>
     */
    public Builder clearChildSaved() {
      bitField0_ = (bitField0_ & ~0x00000800);
      childSaved_ = null;
      if (childSavedBuilder_ != null) {
        childSavedBuilder_.dispose();
        childSavedBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ChildDTO child_saved = 10;</code>
     */
    public ChildDTO.Builder getChildSavedBuilder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return getChildSavedFieldBuilder().getBuilder();
    }
    /**
     * <code>.ChildDTO child_saved = 10;</code>
     */
    public ChildDTOOrBuilder getChildSavedOrBuilder() {
      if (childSavedBuilder_ != null) {
        return childSavedBuilder_.getMessageOrBuilder();
      } else {
        return childSaved_ == null ?
            ChildDTO.getDefaultInstance() : childSaved_;
      }
    }
    /**
     * <code>.ChildDTO child_saved = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder> 
        getChildSavedFieldBuilder() {
      if (childSavedBuilder_ == null) {
        childSavedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ChildDTO, ChildDTO.Builder, ChildDTOOrBuilder>(
                getChildSaved(),
                getParentForChildren(),
                isClean());
        childSaved_ = null;
      }
      return childSavedBuilder_;
    }

    private java.lang.Object number_ = "";
    /**
     * <code>string number = 13;</code>
     * @return The number.
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string number = 13;</code>
     * @return The bytes for number.
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string number = 13;</code>
     * @param value The number to set.
     * @return This builder for chaining.
     */
    public Builder setNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      number_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string number = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumber() {
      number_ = getDefaultInstance().getNumber();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string number = 13;</code>
     * @param value The bytes for number to set.
     * @return This builder for chaining.
     */
    public Builder setNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      number_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CompetitionResponse)
  }

  // @@protoc_insertion_point(class_scope:CompetitionResponse)
  private static final CompetitionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CompetitionResponse();
  }

  public static CompetitionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompetitionResponse>
      PARSER = new com.google.protobuf.AbstractParser<CompetitionResponse>() {
    @java.lang.Override
    public CompetitionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CompetitionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompetitionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CompetitionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

