// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: competition.proto
package org.example.javaFiles;
// Protobuf Java Version: 4.26.1
public interface NewOrBuilder extends
    // @@protoc_insertion_point(interface_extends:New)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sampleId = 1;</code>
   * @return The sampleId.
   */
  java.lang.String getSampleId();
  /**
   * <code>string sampleId = 1;</code>
   * @return The bytes for sampleId.
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();

  /**
   * <code>string number = 2;</code>
   * @return The number.
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 2;</code>
   * @return The bytes for number.
   */
  com.google.protobuf.ByteString
      getNumberBytes();
}
