package org.example.javaFiles;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: competition.protopackage org.example.javaFiles;

// Protobuf Java Version: 4.26.1
public interface RegistrationDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegistrationDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string childId = 1;</code>
   * @return The childId.
   */
  java.lang.String getChildId();
  /**
   * <code>string childId = 1;</code>
   * @return The bytes for childId.
   */
  com.google.protobuf.ByteString
      getChildIdBytes();

  /**
   * <code>string sampleId = 2;</code>
   * @return The sampleId.
   */
  java.lang.String getSampleId();
  /**
   * <code>string sampleId = 2;</code>
   * @return The bytes for sampleId.
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();

  /**
   * <code>string sampleCategory = 3;</code>
   * @return The sampleCategory.
   */
  java.lang.String getSampleCategory();
  /**
   * <code>string sampleCategory = 3;</code>
   * @return The bytes for sampleCategory.
   */
  com.google.protobuf.ByteString
      getSampleCategoryBytes();

  /**
   * <code>string ageCategory = 4;</code>
   * @return The ageCategory.
   */
  java.lang.String getAgeCategory();
  /**
   * <code>string ageCategory = 4;</code>
   * @return The bytes for ageCategory.
   */
  com.google.protobuf.ByteString
      getAgeCategoryBytes();
}
