// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: competition.proto

// Protobuf Java Version: 4.26.1
/**
 * Protobuf type {@code RegistrationDTO}
 */package org.example.javaFiles;
public final class RegistrationDTO extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:RegistrationDTO)
    RegistrationDTOOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      RegistrationDTO.class.getName());
  }
  // Use RegistrationDTO.newBuilder() to construct.
  private RegistrationDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RegistrationDTO() {
    childId_ = "";
    sampleId_ = "";
    sampleCategory_ = "";
    ageCategory_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CompetitionProtobuf.internal_static_RegistrationDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CompetitionProtobuf.internal_static_RegistrationDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RegistrationDTO.class, RegistrationDTO.Builder.class);
  }

  public static final int CHILDID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object childId_ = "";
  /**
   * <code>string childId = 1;</code>
   * @return The childId.
   */
  @java.lang.Override
  public java.lang.String getChildId() {
    java.lang.Object ref = childId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      childId_ = s;
      return s;
    }
  }
  /**
   * <code>string childId = 1;</code>
   * @return The bytes for childId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChildIdBytes() {
    java.lang.Object ref = childId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      childId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SAMPLEID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sampleId_ = "";
  /**
   * <code>string sampleId = 2;</code>
   * @return The sampleId.
   */
  @java.lang.Override
  public java.lang.String getSampleId() {
    java.lang.Object ref = sampleId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sampleId_ = s;
      return s;
    }
  }
  /**
   * <code>string sampleId = 2;</code>
   * @return The bytes for sampleId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSampleIdBytes() {
    java.lang.Object ref = sampleId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sampleId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SAMPLECATEGORY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sampleCategory_ = "";
  /**
   * <code>string sampleCategory = 3;</code>
   * @return The sampleCategory.
   */
  @java.lang.Override
  public java.lang.String getSampleCategory() {
    java.lang.Object ref = sampleCategory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sampleCategory_ = s;
      return s;
    }
  }
  /**
   * <code>string sampleCategory = 3;</code>
   * @return The bytes for sampleCategory.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSampleCategoryBytes() {
    java.lang.Object ref = sampleCategory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sampleCategory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGECATEGORY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ageCategory_ = "";
  /**
   * <code>string ageCategory = 4;</code>
   * @return The ageCategory.
   */
  @java.lang.Override
  public java.lang.String getAgeCategory() {
    java.lang.Object ref = ageCategory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ageCategory_ = s;
      return s;
    }
  }
  /**
   * <code>string ageCategory = 4;</code>
   * @return The bytes for ageCategory.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgeCategoryBytes() {
    java.lang.Object ref = ageCategory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ageCategory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(childId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, childId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sampleId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, sampleId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sampleCategory_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, sampleCategory_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ageCategory_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, ageCategory_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(childId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, childId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sampleId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sampleId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sampleCategory_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, sampleCategory_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ageCategory_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, ageCategory_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RegistrationDTO)) {
      return super.equals(obj);
    }
    RegistrationDTO other = (RegistrationDTO) obj;

    if (!getChildId()
        .equals(other.getChildId())) return false;
    if (!getSampleId()
        .equals(other.getSampleId())) return false;
    if (!getSampleCategory()
        .equals(other.getSampleCategory())) return false;
    if (!getAgeCategory()
        .equals(other.getAgeCategory())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHILDID_FIELD_NUMBER;
    hash = (53 * hash) + getChildId().hashCode();
    hash = (37 * hash) + SAMPLEID_FIELD_NUMBER;
    hash = (53 * hash) + getSampleId().hashCode();
    hash = (37 * hash) + SAMPLECATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getSampleCategory().hashCode();
    hash = (37 * hash) + AGECATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getAgeCategory().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RegistrationDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RegistrationDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RegistrationDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RegistrationDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RegistrationDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RegistrationDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RegistrationDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static RegistrationDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static RegistrationDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static RegistrationDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RegistrationDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static RegistrationDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RegistrationDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RegistrationDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RegistrationDTO)
      RegistrationDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CompetitionProtobuf.internal_static_RegistrationDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CompetitionProtobuf.internal_static_RegistrationDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RegistrationDTO.class, RegistrationDTO.Builder.class);
    }

    // Construct using RegistrationDTO.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      childId_ = "";
      sampleId_ = "";
      sampleCategory_ = "";
      ageCategory_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CompetitionProtobuf.internal_static_RegistrationDTO_descriptor;
    }

    @java.lang.Override
    public RegistrationDTO getDefaultInstanceForType() {
      return RegistrationDTO.getDefaultInstance();
    }

    @java.lang.Override
    public RegistrationDTO build() {
      RegistrationDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public RegistrationDTO buildPartial() {
      RegistrationDTO result = new RegistrationDTO(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(RegistrationDTO result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.childId_ = childId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sampleId_ = sampleId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sampleCategory_ = sampleCategory_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.ageCategory_ = ageCategory_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RegistrationDTO) {
        return mergeFrom((RegistrationDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RegistrationDTO other) {
      if (other == RegistrationDTO.getDefaultInstance()) return this;
      if (!other.getChildId().isEmpty()) {
        childId_ = other.childId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSampleId().isEmpty()) {
        sampleId_ = other.sampleId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSampleCategory().isEmpty()) {
        sampleCategory_ = other.sampleCategory_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAgeCategory().isEmpty()) {
        ageCategory_ = other.ageCategory_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              childId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              sampleId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              sampleCategory_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              ageCategory_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object childId_ = "";
    /**
     * <code>string childId = 1;</code>
     * @return The childId.
     */
    public java.lang.String getChildId() {
      java.lang.Object ref = childId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        childId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string childId = 1;</code>
     * @return The bytes for childId.
     */
    public com.google.protobuf.ByteString
        getChildIdBytes() {
      java.lang.Object ref = childId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        childId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string childId = 1;</code>
     * @param value The childId to set.
     * @return This builder for chaining.
     */
    public Builder setChildId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      childId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string childId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChildId() {
      childId_ = getDefaultInstance().getChildId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string childId = 1;</code>
     * @param value The bytes for childId to set.
     * @return This builder for chaining.
     */
    public Builder setChildIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      childId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object sampleId_ = "";
    /**
     * <code>string sampleId = 2;</code>
     * @return The sampleId.
     */
    public java.lang.String getSampleId() {
      java.lang.Object ref = sampleId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sampleId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sampleId = 2;</code>
     * @return The bytes for sampleId.
     */
    public com.google.protobuf.ByteString
        getSampleIdBytes() {
      java.lang.Object ref = sampleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sampleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sampleId = 2;</code>
     * @param value The sampleId to set.
     * @return This builder for chaining.
     */
    public Builder setSampleId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sampleId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string sampleId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleId() {
      sampleId_ = getDefaultInstance().getSampleId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string sampleId = 2;</code>
     * @param value The bytes for sampleId to set.
     * @return This builder for chaining.
     */
    public Builder setSampleIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sampleId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object sampleCategory_ = "";
    /**
     * <code>string sampleCategory = 3;</code>
     * @return The sampleCategory.
     */
    public java.lang.String getSampleCategory() {
      java.lang.Object ref = sampleCategory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sampleCategory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sampleCategory = 3;</code>
     * @return The bytes for sampleCategory.
     */
    public com.google.protobuf.ByteString
        getSampleCategoryBytes() {
      java.lang.Object ref = sampleCategory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sampleCategory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sampleCategory = 3;</code>
     * @param value The sampleCategory to set.
     * @return This builder for chaining.
     */
    public Builder setSampleCategory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sampleCategory_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string sampleCategory = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleCategory() {
      sampleCategory_ = getDefaultInstance().getSampleCategory();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string sampleCategory = 3;</code>
     * @param value The bytes for sampleCategory to set.
     * @return This builder for chaining.
     */
    public Builder setSampleCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sampleCategory_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object ageCategory_ = "";
    /**
     * <code>string ageCategory = 4;</code>
     * @return The ageCategory.
     */
    public java.lang.String getAgeCategory() {
      java.lang.Object ref = ageCategory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ageCategory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ageCategory = 4;</code>
     * @return The bytes for ageCategory.
     */
    public com.google.protobuf.ByteString
        getAgeCategoryBytes() {
      java.lang.Object ref = ageCategory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ageCategory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ageCategory = 4;</code>
     * @param value The ageCategory to set.
     * @return This builder for chaining.
     */
    public Builder setAgeCategory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ageCategory_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string ageCategory = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgeCategory() {
      ageCategory_ = getDefaultInstance().getAgeCategory();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string ageCategory = 4;</code>
     * @param value The bytes for ageCategory to set.
     * @return This builder for chaining.
     */
    public Builder setAgeCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ageCategory_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RegistrationDTO)
  }

  // @@protoc_insertion_point(class_scope:RegistrationDTO)
  private static final RegistrationDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RegistrationDTO();
  }

  public static RegistrationDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegistrationDTO>
      PARSER = new com.google.protobuf.AbstractParser<RegistrationDTO>() {
    @java.lang.Override
    public RegistrationDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RegistrationDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegistrationDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public RegistrationDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

