// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: competition.proto
package org.example.javaFiles;
// Protobuf Java Version: 4.26.1
public interface SampleDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SampleDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string sampleCategory = 2;</code>
   * @return The sampleCategory.
   */
  java.lang.String getSampleCategory();
  /**
   * <code>string sampleCategory = 2;</code>
   * @return The bytes for sampleCategory.
   */
  com.google.protobuf.ByteString
      getSampleCategoryBytes();

  /**
   * <code>string ageCategory = 3;</code>
   * @return The ageCategory.
   */
  java.lang.String getAgeCategory();
  /**
   * <code>string ageCategory = 3;</code>
   * @return The bytes for ageCategory.
   */
  com.google.protobuf.ByteString
      getAgeCategoryBytes();
}
